// Copyright (c) fmaerten@gmail.com
// License: MIT

// Expanded (reflection-free) C# backend. Included by inline/generate.hxx after
// backends/csharp.h (reuses csharp_wrapper / cs_ident / CS_CSPROJ / CS_README)
// and backends/python.h (reuses qualify_std), plus the shared render
// helpers (jsonable_*, render_meta, write_file, readme_body_of).
//
// The generated auto_csharp.cpp registers every field / method / constructor by
// pointer, so the runtime deduces the marshalled types from the pointer type —
// no reflection at the target's compile time. The C# side is the same as the
// thin backend's.

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // Stock-toolchain CMake: C++20 (member-pointer + class-type NTTPs for the
        // runtime's get_field<&T::f> / fixed_str), the user's headers, and
        // rosetta's include dir purely for the reflection-free runtime/csharp.h.
        // No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view CSX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain shared library reached from .NET via P/Invoke. NO C++26, NO reflection;
# rosetta's include dir is on the path only for the header-only runtime/csharp.h.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

include(FetchContent)
FetchContent_Declare(json
    GIT_REPOSITORY https://github.com/nlohmann/json.git
    GIT_TAG        v3.11.3)
FetchContent_MakeAvailable(json)

add_library({{LIB}} SHARED auto_csharp.cpp)
set_target_properties({{LIB}} PROPERTIES
    POSITION_INDEPENDENT_CODE ON
    CXX_VISIBILITY_PRESET hidden
    VISIBILITY_INLINES_HIDDEN ON)

target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}}
    {{ROSETTA_INCLUDE}})
{{USER_LIB_BLOCK}}
target_link_libraries({{LIB}} PRIVATE nlohmann_json::nlohmann_json)
)CMK";

        // The fixed part of the native shim: ensure_registered + dup_cstr + the
        // exported C ABI. Identical to the thin backend's (only register_all and
        // the includes differ between the two), so both speak the same protocol.
        constexpr std::string_view CSX_ABI = R"CPP(
void ensure_registered() {
    static std::once_flag once;
    std::call_once(once, [] { register_all(); });
}

// Copy a std::string into a malloc'd C string; the C# side releases it via
// rosetta_csharp_free. Returns nullptr only on allocation failure.
char *dup_cstr(const std::string &s) {
    char *p = static_cast<char *>(std::malloc(s.size() + 1));
    if (p) {
        std::memcpy(p, s.c_str(), s.size() + 1);
    }
    return p;
}

} // namespace

extern "C" {

ROSETTA_CS_EXPORT int rosetta_csharp_create(const char *type, const char *args) {
    ensure_registered();
    return rosetta::cs::api_create(type, args);
}

ROSETTA_CS_EXPORT int rosetta_csharp_destroy(const char *type, int id) {
    ensure_registered();
    return rosetta::cs::api_destroy(type, id) ? 1 : 0;
}

ROSETTA_CS_EXPORT char *rosetta_csharp_get_field(const char *type, int id, const char *field) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_get(type, id, field));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_set_field(const char *type, int id, const char *field,
                                                 const char *value) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_set(type, id, field, value));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_method(const char *type, int id, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_call(type, id, method, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_static(const char *type, const char *method,
                                                   const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_scall(type, method, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_call_function(const char *name, const char *args) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_function(name, args));
}

ROSETTA_CS_EXPORT char *rosetta_csharp_enum_values(const char *type) {
    ensure_registered();
    return dup_cstr(rosetta::cs::api_enum(type));
}

ROSETTA_CS_EXPORT void rosetta_csharp_free(char *p) { std::free(p); }

} // extern "C"
)CPP";

        // A range bound as a `double` literal. set_field_ranged's Lo/Hi are
        // `double` NTTPs, so an integer literal (0) would be ill-formed there —
        // always force a decimal point.
        // ---- the C# wrapper surface -------------------------------------------
        // Lived in the thin C# backend until it was removed. Both backends
        // emitted the SAME .cs wrapper / .csproj / README; only the native
        // side differed, so this half moved here wholesale.
        constexpr std::string_view CS_README = R"MD(# `{{LIB}}` ({{BACKEND}})

Auto-generated C# bindings. Two pieces work together:

- **`auto_csharp.cpp`** → a native shared library exposing a flat C ABI
  (`rosetta_csharp_*`). {{TOOLCHAIN}}
- **`{{LIB}}.cs`** → idiomatic C# wrappers. Each class is a handle into the
  native instance store; property and method access is a JSON round-trip through
  the C ABI via P/Invoke (`System.Text.Json` does the (de)serialisation).

## Build

```sh
# 1. the native library (produces lib{{LIB}}.{dylib,so} / {{LIB}}.dll)
cmake -S . -B build && cmake --build build

# 2. the .NET assembly
dotnet build {{LIB}}.csproj
```

## Run

The .NET loader must find the native library at run time. Point it at the CMake
build dir (or copy `lib{{LIB}}.*` next to your executable):

```sh
# macOS
DYLD_LIBRARY_PATH=build dotnet run
# Linux
LD_LIBRARY_PATH=build dotnet run
```

## Use

```csharp
using {{NS}};

using var p = new Person();   // IDisposable — frees the native instance
p.name = "Alice";
System.Console.WriteLine(p.greet("Hi"));
```

Boundary types: scalars, `bool`, `string`, enums (by name), and `List<…>` of
those. Members using any other type are omitted from both sides.

)MD";

        constexpr std::string_view CS_CSPROJ = R"CSPROJ(<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
    <AssemblyName>{{LIB}}</AssemblyName>
    <RootNamespace>{{NS}}</RootNamespace>
  </PropertyGroup>

</Project>
)CSPROJ";

        // -------- C# rendering helpers --------

        // Sanitise an arbitrary library name into a C# identifier usable as a
        // namespace (letters / digits / underscore; must not start with a digit).
        inline std::string cs_ident(const std::string &s) {
            auto is_alnum = [](char ch) {
                return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                       (ch >= '0' && ch <= '9');
            };
            auto is_digit = [](char ch) { return ch >= '0' && ch <= '9'; };
            std::string out;
            for (char ch : s) {
                out += (is_alnum(ch) ? ch : '_');
            }
            if (out.empty() || is_digit(out.front())) {
                out.insert(out.begin(), '_');
            }
            return out;
        }

        // Render a neutral GenType as the C# type the wrapper marshals it to.
        // Only ever called for jsonable types; the fallback is defensive.
        inline std::string cs_type(const GenType &t, const GenContext &c) {
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "string") {
                return "string";
            }
            if (t.kind == "number") {
                return t.integer ? "long" : "double";
            }
            if (t.kind == "enum") {
                return t.object.empty() ? "long" : exposed_object_of(t, c);
            }
            if (t.kind == "vector") {
                return "System.Collections.Generic.List<" +
                       (t.element.empty() ? std::string("object")
                                          : cs_type(t.element.front(), c)) +
                       ">";
            }
            return "object";
        }

        // "double arg0, double arg1"
        // A parameter name safe to DECLARE in C#. The IR carries the identifier
        // the C++ declaration used, and C++ is happy to name a parameter
        // `string`, `event`, `params` or `object` — each a keyword here, and a
        // syntax error in the generated wrapper. Such a name reverts to the
        // positional form. Both the declaration and the forwarding call go
        // through this, so they cannot disagree.
        inline std::string cs_ident(const std::string &name, std::size_t index) {
            static const char *kw[] = {
                "abstract","as","base","bool","break","byte","case","catch","char","checked",
                "class","const","continue","decimal","default","delegate","do","double","else",
                "enum","event","explicit","extern","false","finally","fixed","float","for",
                "foreach","goto","if","implicit","in","int","interface","internal","is","lock",
                "long","namespace","new","null","object","operator","out","override","params",
                "private","protected","public","readonly","ref","return","sbyte","sealed","short",
                "sizeof","stackalloc","static","string","struct","switch","this","throw","true",
                "try","typeof","uint","ulong","unchecked","unsafe","ushort","using","virtual",
                "void","volatile","while",
            };
            for (const char *k : kw) {
                if (name == k) {
                    return "arg" + std::to_string(index);
                }
            }
            return name.empty() ? "arg" + std::to_string(index) : name;
        }

        // A C# XML doc comment. Rendered line by line: `///` documents ONE line,
        // so a harvested multi-paragraph comment written on a single one would
        // spill its tail into the code. `<` and `&` are escaped because this is
        // XML, and a doc mentioning `std::vector<double>` is otherwise malformed.
        inline std::string cs_doc(const std::string &doc, const std::string &indent) {
            if (doc.empty()) {
                return {};
            }
            std::string esc;
            for (char ch : doc) {
                if (ch == '<') {
                    esc += "&lt;";
                } else if (ch == '>') {
                    esc += "&gt;";
                } else if (ch == '&') {
                    esc += "&amp;";
                } else {
                    esc += ch;
                }
            }
            // A blank line is written as "///", not "/// " — the paragraph break
            // has to survive, trailing whitespace does not.
            const auto doc_line = [&indent](std::string &o, const std::string &l) {
                o += indent + (l.empty() ? "///" : "/// " + l) + "\n";
            };
            std::string out = indent + "/// <summary>\n";
            std::string line;
            for (char ch : esc) {
                if (ch == '\n') {
                    doc_line(out, line);
                    line.clear();
                    continue;
                }
                line += ch;
            }
            doc_line(out, line);
            // No trailing newline: every call site places this block relative to
            // the declaration it documents and adds its own.
            return out + indent + "/// </summary>";
        }

        inline std::string cs_param_sig(const std::vector<GenParam> &ps, const GenContext &c) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + cs_type(ps[i].type, c) + " " + cs_ident(ps[i].name, i);
            }
            return s;
        }

        // The argument list forwarded to Rt.Args(...), matching cs_param_sig.
        inline std::string cs_arg_names(const std::vector<GenParam> &ps) {
            std::string s;
            for (std::size_t i = 0; i < ps.size(); ++i) {
                s += (i ? ", " : "") + cs_ident(ps[i].name, i);
            }
            return s;
        }

        inline bool cs_ctor_jsonable(const std::vector<GenParam> &ps) {
            for (const auto &p : ps) {
                if (!jsonable_type(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // The fixed runtime helpers (Native P/Invoke surface + Rt marshalling +
        // exception type), emitted once per module.
        inline std::string cs_runtime(const GenContext &c) {
            const std::string lib = c.lib;
            std::string       s;
            s += "    public class RosettaException : System.Exception {\n";
            s += "        public RosettaException(string message) : base(message) { }\n";
            s += "    }\n\n";

            s += "    internal static class Native {\n";
            s += "        private const string LIB = \"" + lib + "\";\n";
            auto str = [](const char *n) {
                return std::string("[System.Runtime.InteropServices.MarshalAs("
                                   "System.Runtime.InteropServices.UnmanagedType.LPUTF8Str)] string ") +
                       n;
            };
            const std::string dll = "        [System.Runtime.InteropServices.DllImport(LIB, "
                                    "CallingConvention = "
                                    "System.Runtime.InteropServices.CallingConvention.Cdecl)]\n";
            s += dll + "        internal static extern int rosetta_csharp_create(" + str("type") +
                 ", " + str("args") + ");\n";
            s += dll + "        internal static extern int rosetta_csharp_destroy(" + str("type") +
                 ", int id);\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_get_field(" +
                 str("type") + ", int id, " + str("field") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_set_field(" +
                 str("type") + ", int id, " + str("field") + ", " + str("value") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_method(" +
                 str("type") + ", int id, " + str("method") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_static(" +
                 str("type") + ", " + str("method") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_call_function(" +
                 str("name") + ", " + str("args") + ");\n";
            s += dll +
                 "        internal static extern System.IntPtr rosetta_csharp_enum_values(" +
                 str("type") + ");\n";
            s += dll +
                 "        internal static extern void rosetta_csharp_free(System.IntPtr p);\n";
            s += "    }\n\n";

            s += R"CS(    internal static class Rt {
        // Enums cross the boundary as their underlying integer (the native side
        // marshals them that way), which is System.Text.Json's default for
        // C# enums — so no custom converter is needed.
        private static readonly System.Text.Json.JsonSerializerOptions Opts =
            new System.Text.Json.JsonSerializerOptions();

        private static string Take(System.IntPtr p) {
            if (p == System.IntPtr.Zero) return "";
            string s = System.Runtime.InteropServices.Marshal.PtrToStringUTF8(p) ?? "";
            Native.rosetta_csharp_free(p);
            return s;
        }

        // Parse the {"ok":…,"value":…,"error":…} envelope, throwing on failure.
        private static System.Text.Json.JsonElement Unwrap(System.IntPtr p) {
            string env = Take(p);
            using var doc = System.Text.Json.JsonDocument.Parse(env);
            var root = doc.RootElement;
            if (!root.GetProperty("ok").GetBoolean()) {
                string msg = root.TryGetProperty("error", out var e) ? (e.GetString() ?? "error") : "error";
                throw new RosettaException(msg);
            }
            return root.GetProperty("value").Clone();
        }

        internal static T Get<T>(System.IntPtr p) =>
            System.Text.Json.JsonSerializer.Deserialize<T>(Unwrap(p).GetRawText(), Opts)!;
        internal static void Void(System.IntPtr p) { Unwrap(p); }
        internal static string Args(params object?[] a) =>
            System.Text.Json.JsonSerializer.Serialize(a, Opts);
        internal static string Ser(object? v) =>
            System.Text.Json.JsonSerializer.Serialize(v, Opts);
        internal static int New(string type, string args) {
            int id = Native.rosetta_csharp_create(type, args);
            if (id < 0) throw new RosettaException("failed to construct " + type);
            return id;
        }
    }

)CS";
            return s;
        }

        // One handle-backed wrapper class.
        inline std::string cs_class(const GenClass &k, const GenContext &c) {
            std::string s;
            if (!k.doc.empty()) {
                s += "    // " + exposed_of(k) + "\n";
            }
            s += "    public sealed class " + exposed_of(k) + " : System.IDisposable {\n";
            s += "        private int _id;\n";
            s += "        private const string _t = \"" + exposed_of(k) + "\";\n\n";

            // Constructors. Dedupe by C# signature so two C++ ctors that erase to
            // the same arity/types don't produce a duplicate member.
            std::vector<std::string> seen_sigs;
            auto                     emit_ctor = [&](const std::vector<GenParam> &ps) {
                const std::string sig = cs_param_sig(ps, c);
                for (const auto &s2 : seen_sigs) {
                    if (s2 == sig) {
                        return;
                    }
                }
                seen_sigs.push_back(sig);
                const std::string args =
                    ps.empty() ? std::string("\"[]\"") : "Rt.Args(" + cs_arg_names(ps) + ")";
                s += "        public " + exposed_of(k) + "(" + sig + ") { _id = Rt.New(_t, " + args +
                     "); }\n";
            };
            if (k.is_default_constructible) {
                emit_ctor({});
            }
            for (const auto &ct : k.ctors) {
                if (!ct.empty() && cs_ctor_jsonable(ct)) {
                    emit_ctor(ct);
                }
            }
            if (seen_sigs.empty()) {
                // No JSON-marshalable constructor — block the implicit public
                // parameterless ctor so a broken (id 0) instance can't be made.
                s += "        private " + exposed_of(k) +
                     "() { } // no JSON-marshalable constructor\n";
            }

            s += "\n        public void Dispose() {\n";
            s += "            if (_id > 0) { Native.rosetta_csharp_destroy(_t, _id); _id = 0; }\n";
            s += "            System.GC.SuppressFinalize(this);\n";
            s += "        }\n";
            s += "        ~" + exposed_of(k) +
                 "() { if (_id > 0) Native.rosetta_csharp_destroy(_t, _id); }\n";

            // Fields → properties.
            for (const auto &f : k.fields) {
                if (!jsonable_type(f.type)) {
                    continue;
                }
                const std::string ty = cs_type(f.type, c);
                if (!f.doc.empty()) {
                    s += "\n" + cs_doc(f.doc, "        ");
                }
                s += "\n        public " + ty + " " + f.name + " {\n";
                s += "            get => Rt.Get<" + ty +
                     ">(Native.rosetta_csharp_get_field(_t, _id, \"" + f.name + "\"));\n";
                if (!f.is_readonly) {
                    s += "            set => Rt.Void(Native.rosetta_csharp_set_field(_t, _id, \"" +
                         f.name + "\", Rt.Ser(value)));\n";
                }
                s += "        }\n";
            }

            // Methods.
            for (const auto &m : k.methods) {
                if (m.is_extension || !jsonable_method(m)) { // extensions: no member pointer
                    continue;
                }
                const std::string sig    = cs_param_sig(m.params, c);
                const std::string names  = cs_arg_names(m.params);
                const std::string argexp = "Rt.Args(" + names + ")";
                if (!m.doc.empty()) {
                    s += "\n" + cs_doc(m.doc, "        ");
                }
                s += "\n        public " + std::string(m.is_static ? "static " : "");
                const std::string callexpr =
                    m.is_static
                        ? "Native.rosetta_csharp_call_static(_t, \"" + m.name + "\", " + argexp + ")"
                        : "Native.rosetta_csharp_call_method(_t, _id, \"" + m.name + "\", " +
                              argexp + ")";
                if (m.ret.kind == "void") {
                    s += "void " + m.name + "(" + sig + ") => Rt.Void(" + callexpr + ");\n";
                } else {
                    s += cs_type(m.ret, c) + " " + m.name + "(" + sig + ") => Rt.Get<" +
                         cs_type(m.ret, c) + ">(" + callexpr + ");\n";
                }
            }

            s += "    }\n\n";
            return s;
        }

        inline std::string csharp_wrapper(const GenContext &c) {
            const std::string ns = cs_ident(c.lib);
            std::string       s  = "// Generated by rosetta::generate — do not edit by hand.\n";
            s += "#nullable enable\n\n";
            s += "namespace " + ns + " {\n\n";

            for (const auto &e : c.enums) {
                if (!e.doc.empty()) {
                    s += "    // " + exposed_of(e) + "\n";
                }
                s += "    public enum " + exposed_of(e) + " {\n";
                for (const auto &v : e.values) {
                    s += "        " + v.name + " = " + std::to_string(v.value) + ",\n";
                }
                s += "    }\n\n";
            }

            s += cs_runtime(c);

            for (const auto &k : c.classes) {
                s += cs_class(k, c);
            }

            // Free functions → a static facade class.
            bool any_fn = false;
            for (const auto &f : c.functions) {
                if (jsonable_function(f)) {
                    any_fn = true;
                    break;
                }
            }
            if (any_fn) {
                s += "    public static class " + cs_ident(c.lib) + "Functions {\n";
                for (const auto &f : c.functions) {
                    if (!jsonable_function(f)) {
                        continue;
                    }
                    const std::string argexp = "Rt.Args(" + cs_arg_names(f.params) + ")";
                    const std::string call =
                        "Native.rosetta_csharp_call_function(\"" + f.name + "\", " + argexp + ")";
                    if (!f.doc.empty()) {
                        s += cs_doc(f.doc, "        ") + "\n";
                    }
                    s += "        public static ";
                    if (f.ret.kind == "void") {
                        s += "void " + f.name + "(" + cs_param_sig(f.params, c) + ") => Rt.Void(" +
                             call + ");\n";
                    } else {
                        s += cs_type(f.ret, c) + " " + f.name + "(" + cs_param_sig(f.params, c) +
                             ") => Rt.Get<" + cs_type(f.ret, c) + ">(" + call + ");\n";
                    }
                }
                s += "    }\n\n";
            }

            s += "}\n";
            return s;
        }

        inline std::string csx_double_lit(double d) {
            std::string s = num_str(d);
            if (s.find('.') == std::string::npos && s.find('e') == std::string::npos &&
                s.find('E') == std::string::npos) {
                s += ".0";
            }
            return s;
        }

        // One class, expanded into an explicit TypeOps registration block.
        inline std::string csx_class(const GenClass &k) {
            // C++ spellings use the qualified name; the registry key is the
            // exposed one, matching the C# wrapper's `_t` (manifest "expose").
            const std::string t = qualified_of(k);
            std::string       s = "    {\n        rosetta::cs::TypeOps ops;\n";
            s += "        ops.destroy = &rosetta::cs::destroy_inst<" + t + ">;\n";
            if (k.is_default_constructible) {
                s += "        ops.create  = &rosetta::cs::create_default<" + t + ">;\n";
            }

            // Fields → get + (readonly / ranged / plain) set.
            for (const auto &f : k.fields) {
                if (!jsonable_type(f.type)) {
                    continue;
                }
                const std::string mp = "&" + t + "::" + f.name;
                s += "        ops.get[\"" + f.name + "\"] = &rosetta::cs::get_field<" + mp + ">;\n";
                if (f.is_readonly) {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::cs::set_field_readonly<" +
                         mp + ", \"" + f.name + "\">;\n";
                } else if (f.range.has && f.type.kind == "number") {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::cs::set_field_ranged<" +
                         mp + ", \"" + f.name + "\", " + csx_double_lit(f.range.min) + ", " +
                         csx_double_lit(f.range.max) + ">;\n";
                } else {
                    s += "        ops.set[\"" + f.name + "\"] = &rosetta::cs::set_field<" + mp +
                         ">;\n";
                }
            }

            // Methods → call (instance) / call_function (static; a static member
            // is a plain function pointer).
            for (const auto &m : k.methods) {
                // `ops.call` is a map keyed by the method name, so a second
                // entry for the same name overwrites the first rather than
                // adding an overload — and the host language's marshalling goes
                // through JSON, which carries no C++ types to dispatch on. Only
                // the first-declared overload binds.
                if (!coverage::emit_overload(coverage::overloads::first_only, "csharp", k, m)) {
                    continue;
                }
                if (m.is_extension || !jsonable_method(m)) { // extensions: no member pointer
                    coverage::note_skip("csharp", k, m,
                                        m.is_extension ? "extension_has_no_member_pointer"
                                                       : "unmarshalable_signature",
                                        m.is_extension
                                            ? "this backend dispatches through a member pointer, "
                                              "which an extension method does not have"
                                            : "a type in this signature has no JSON "
                                              "representation for the op table");
                    continue;
                }
                // px_member_pointer, not the bare `&T::name`: for an overloaded
                // name the bare form names the whole set, and the template
                // argument below would not compile at all. (That was true before
                // the walk started emitting every overload too — the entry that
                // reached the IR was already unbindable here.)
                const std::string mp = px_member_pointer(k, m);
                if (m.is_static) {
                    s += "        ops.scall[\"" + m.name + "\"] = &rosetta::cs::call_function<" + mp +
                         ">;\n";
                } else {
                    s += "        ops.call[\"" + m.name + "\"] = &rosetta::cs::call_method<" + mp +
                         ">;\n";
                }
                coverage::note_bound("csharp", k, m);
            }

            // Constructors → construct<T, Args...>, keyed by arity. Skip 0-arg
            // (handled by ops.create) and any whose params aren't marshalable.
            for (std::size_t i = 0; i < k.ctor_param_cpp.size(); ++i) {
                const auto &ir = k.ctors[i];
                if (ir.empty()) {
                    continue;
                }
                bool ok = true;
                for (const auto &p : ir) {
                    ok = ok && jsonable_type(p.type);
                }
                if (!ok) {
                    continue;
                }
                std::string types;
                for (const auto &spelling : k.ctor_param_cpp[i]) {
                    types += ", " + qualify_std(spelling);
                }
                s += "        ops.ctors[" + std::to_string(ir.size()) +
                     "] = &rosetta::cs::construct<" + t + types + ">;\n";
            }

            s += "        rosetta::cs::registry()[\"" + exposed_of(k) + "\"] = std::move(ops);\n    }\n";
            return s;
        }

        inline std::string csharp_expanded_registrations(const GenContext &c) {
            std::string s;
            // Enums: literal name -> value map (reflection-free).
            for (const auto &e : c.enums) {
                s += "    rosetta::cs::enums()[\"" + exposed_of(e) + "\"] = rosetta::cs::json{";
                for (std::size_t i = 0; i < e.values.size(); ++i) {
                    s += (i ? ", " : "") + std::string("{\"") + e.values[i].name + "\", " +
                         std::to_string(e.values[i].value) + "}";
                }
                s += "};\n";
            }
            for (const auto &k : c.classes) {
                s += csx_class(k);
            }
            for (const auto &f : c.functions) {
                if (jsonable_function(f)) {
                    coverage::note_bound_function("csharp", f);
                    s += "    rosetta::cs::functions()[\"" + f.name +
                         "\"] = &rosetta::cs::call_function<" + fn_addr(f) + ">;\n";
                } else {
                    coverage::note_skip_function("csharp", f, "unmarshalable_signature",
                                                 "a type in this signature has no JSON "
                                                 "marshalling");
                }
            }
            return s;
        }

        inline std::string csharp_expanded_source(const GenContext &c) {
            std::string out =
                "// Generated by rosetta::generate (expanded, reflection-free) — "
                "do not edit by hand.\n";
            out += "#include <rosetta/runtime/csharp.h>\n";
            out += "#include <cstdlib>\n#include <cstring>\n#include <mutex>\n#include <string>\n";
            // User headers (deduped) — the only thing the shim needs besides the
            // runtime; no rosetta/annotations.h (these headers are stock C++).
            auto add = [&](const std::string &h) { append_include(out, h); };
            out += init_includes(c);
            for (const auto &k : c.classes) {
                add(k.header);
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += "\nnamespace {\n\nvoid register_all() {\n";
            out += csharp_expanded_registrations(c);
            out += "}\n";
            out += CSX_ABI;
            return out;
        }

        inline std::string CSharp::render(const GenContext &c) const {
            return csharp_expanded_source(c);
        }

        inline void CSharp::emit(const GenContext &c) const {
            auto dir = c.out_dir / "csharp";
            write_file(dir / "auto_csharp.cpp", csharp_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(CSX_CMAKE, c));
            // The C# wrapper / project are identical to the thin backend's.
            write_file(dir / (c.lib + ".cs"), csharp_wrapper(c));
            write_file(dir / (c.lib + ".csproj"),
                       subst(CS_CSPROJ, {{"LIB", c.lib}, {"NS", cs_ident(c.lib)}}));
            const std::string doc =
                subst(CS_README,
                      {{"LIB", c.lib},
                       {"NS", cs_ident(c.lib)},
                       {"BACKEND", "csharp"},
                       {"TOOLCHAIN",
                        "Builds with a stock C++20 compiler — no reflection toolchain needed."}}) +
                readme_body_of(c.classes);
            write_file(dir / "README.md", doc);
        }

    } // namespace backend
} // namespace rosetta
