// Copyright (c) fmaerten@gmail.com
// License: MIT

// Markdown documentation backend — implementation. A *pure-data* backend: it
// consumes the reflection IR that `generate` erases into GenClass and renders a
// single Markdown reference. The per-class fragments come from
// gen_detail::class_markdown (also used for READMEs and rosetta::to_markdown);
// this stitches them into one library document. render() returns the string;
// emit() writes it to <out>/markdown/<lib>.md. Included by inline/generate.hxx
// (via backends/markdown.h).

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        inline std::string Markdown::render(const GenContext &c) const {
            std::string out = "<!-- Generated by rosetta::generate — do not edit by hand. -->\n";
            out += "# `" + c.lib + "` API reference\n\n";

            // Table of contents — one bullet per class then per enum,
            // linking to its section. GitHub anchors lowercase the heading.
            out += "## Contents\n\n";
            for (const auto &k : c.classes) {
                out += "- [" + exposed_of(k) + "](#" + exposed_of(k) + ")\n";
            }
            for (const auto &e : c.enums) {
                out += "- [" + exposed_of(e) + "](#" + exposed_of(e) + ") _(enum)_\n";
            }
            if (!c.functions.empty()) {
                out += "- [Functions](#Functions)\n";
            }
            out += "\n";

            // Each class's, then each enum's, per-entity markdown fragment
            // (a `# <Name>` heading plus its body), separated by rules.
            bool first   = true;
            auto section = [&](const std::string &doc) {
                if (!first) {
                    out += "\n---\n\n";
                }
                first = false;
                out += doc;
                if (!out.empty() && out.back() != '\n') {
                    out += "\n";
                }
            };
            for (const auto &k : c.classes) {
                section(k.doc);
            }
            for (const auto &e : c.enums) {
                section(e.doc);
            }

            // Free functions, gathered under one section.
            if (!c.functions.empty()) {
                std::string fdoc = "# Functions\n\n";
                for (const auto &f : c.functions) {
                    fdoc += "### `" + f.name + "(";
                    for (std::size_t i = 0; i < f.params.size(); ++i) {
                        fdoc += (i ? ", " : "") + readable_param(f.params[i]);
                    }
                    fdoc += ") → " + readable_type(f.ret) + "`\n\n";
                    if (!f.doc.empty()) {
                        fdoc += f.doc + "\n\n";
                    }
                    // Same shape as a method's entry (see class_markdown): one
                    // line per documented argument, then the return.
                    bool any_pdoc = false;
                    for (const auto &p : f.params) {
                        any_pdoc = any_pdoc || !p.doc.empty();
                    }
                    if (any_pdoc) {
                        for (const auto &p : f.params) {
                            if (!p.doc.empty()) {
                                fdoc += "- `" + p.name + "` — " + p.doc + "\n";
                            }
                        }
                        fdoc += "\n";
                    }
                    if (!f.returns.empty()) {
                        fdoc += "*Returns:* " + f.returns + "\n\n";
                    }
                }
                section(fdoc);
            }
            return out;
        }

        inline void Markdown::emit(const GenContext &c) const {
            write_file(c.out_dir / "markdown" / (c.lib + ".md"), render(c));
        }

    } // namespace backend

    template <typename... Ts> inline std::string to_markdown(std::string lib) {
        return backend::Markdown{}.render(gen_detail::make_context<Ts...>(std::move(lib)));
    }

} // namespace rosetta
