// Copyright (c) fmaerten@gmail.com
// License: MIT

// Expanded (reflection-free) nanobind backend. Included by inline/generate.hxx
// after backends/nanobind.h and backends/python.h (whose qualify_std()
// it reuses), plus the shared render helpers (subst / num_str / render_meta /
// write_file).

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // A stock-toolchain CMake: C++17, the pip `nanobind` package, the user's
        // include dir only. No clang-p2996, no -freflection, no -nostdlib++.
        constexpr std::string_view NANOBINDX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Plain nanobind: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

execute_process(
    COMMAND {{PYTHON_CMD}} -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)

# Development.SABIModule is what defines the Python::SABIModule target, and
# nanobind silently drops a STABLE_ABI request when that target is missing
# (nanobind-config.cmake: "Stable ABI builds require CPython >= 3.12 and
# Python::SABIModule"). Without it ROSETTA_STABLE_ABI below is accepted and
# then ignored, so the module builds as cpython-3XX while the wheel is still
# tagged abi3 — exactly the mismatch the pyproject comment warns about.
# Optional, not required: PyPy and free-threaded builds have no SABI, and
# nanobind already degrades to a per-version module there.
find_package(Python {{PYTHON_MIN}} COMPONENTS Interpreter Development.Module
                                   OPTIONAL_COMPONENTS Development.SABIModule REQUIRED)

# Prefer the nanobind CMake package shipped with the pip/`nanobind` module,
# fall back to fetching a pinned release.
if(NOT nanobind_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -c "import nanobind; print(nanobind.cmake_dir())"
        OUTPUT_VARIABLE nanobind_DIR
        RESULT_VARIABLE _nanobind_probe
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _nanobind_probe EQUAL 0)
        set(nanobind_DIR "")
    endif()
endif()
if(nanobind_DIR)
    find_package(nanobind CONFIG REQUIRED)
else()
    include(FetchContent)
    FetchContent_Declare(
        nanobind
        GIT_REPOSITORY https://github.com/wjakob/nanobind.git
        GIT_TAG v2.13.0)
    FetchContent_MakeAvailable(nanobind)
endif()

# Build against CPython's stable ABI, so ONE wheel serves every 3.12+
# interpreter instead of one per minor version. Off by default: it only pays
# off when packaging, and it constrains the module to the limited API. The
# generated pyproject.toml turns it on for wheel builds on 3.12+.
option(ROSETTA_STABLE_ABI "Build against CPython's stable ABI (abi3)" OFF)
if(ROSETTA_STABLE_ABI)
    nanobind_add_module({{LIB}} NB_STATIC STABLE_ABI auto_nanobind.cpp)
else()
    nanobind_add_module({{LIB}} NB_STATIC auto_nanobind.cpp)
endif()

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}})
{{USER_LIB_BLOCK}}
# Wheel builds (scikit-build-core sets SKBUILD) package what CMake *installs*,
# so the module must be installed at the wheel root for `import {{LIB}}` to work.
install(TARGETS {{LIB}} LIBRARY DESTINATION . RUNTIME DESTINATION .)

# Convenience for the in-tree build only: drop the module next to the sources so
# it can be imported from this directory. Skipped under SKBUILD, whose build tree
# is a throw-away temp copy.
if(NOT SKBUILD)
    add_custom_command(TARGET {{LIB}} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy
            $<TARGET_FILE:{{LIB}}>
            ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
endif()
{{OUT_DIR_BLOCK}}
)CMK";

        // pyproject.toml driving the wheel build, the nanobind counterpart of
        // PYX_PYPROJECT. scikit-build-core runs the CMakeLists above unchanged.
        //
        // The override block is what makes nanobind worth packaging: on 3.12+
        // it flips ROSETTA_STABLE_ABI on and tags the wheel abi3, so a single
        // artifact covers every later CPython. The two must move together —
        // tagging abi3 without the limited-API build would produce a wheel that
        // installs on 3.13 and crashes — which is why the tag lives behind the
        // same version predicate as the define, not in the base config.
        constexpr std::string_view NANOBINDX_PYPROJECT =
            R"TOML(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Wheel build: `./make_wheel.sh`, or `python3 -m build --wheel`.
[build-system]
requires = ["scikit-build-core>=0.10", "nanobind>=2.0"]
build-backend = "scikit_build_core.build"

[project]
name = "{{LIB}}"
version = "{{VERSION}}"
description = "Auto-generated nanobind bindings for {{LIB}}."
requires-python = "{{REQUIRES_PYTHON}}"

[tool.scikit-build]
cmake.version = ">=3.18"
cmake.build-type = "Release"
# The extension module is installed at the wheel root by CMake's install() —
# there is no Python package directory to copy alongside it.
wheel.packages = []
sdist.include = ["auto_nanobind.cpp", "CMakeLists.txt"]

# On 3.12+ build against the stable ABI and tag the wheel abi3: one wheel then
# serves every later CPython. Below 3.12 nanobind's STABLE_ABI is unavailable,
# so the wheel stays tagged for the exact interpreter that built it.
[[tool.scikit-build.overrides]]
if.python-version = ">=3.12"
wheel.py-api = "cp312"
cmake.define.ROSETTA_STABLE_ABI = "ON"
)TOML";

        // Build/Use section for the generated README — kept next to
        // NANOBINDX_CMAKE so the doc can't drift from the template it
        // describes. Unlike the thin nanobind backend the source is
        // pre-expanded: plain C++17 nanobind, any stock compiler, no
        // clang-p2996 and no rosetta headers.
        constexpr std::string_view NANOBINDX_README_BUILD = R"MD(## Build

The emitted source is plain C++17 nanobind — any stock compiler works; no
reflection toolchain, no rosetta headers. nanobind is taken from an installed
copy when available (`pip install nanobind`); otherwise CMake fetches a pinned
release at configure time (network access needed on the first configure).

```sh
cmake -S . -B build && cmake --build build
```

## Use

A post-build step copies the module next to the sources, so from this directory:

```sh
python3 -c "import {{LIB}}"
```)MD";

        // {{ABI_NOTE}} for PYX_README_WHEEL, the nanobind flavour: unlike
        // pybind11 this backend can ship one wheel for every 3.12+ CPython.
        constexpr std::string_view NANOBINDX_ABI_NOTE =
            R"MD(On CPython 3.12+ the wheel is built against the stable ABI and tagged `abi3`, so
a single artifact covers every later interpreter — no per-version rebuild. Below
3.12 the stable ABI is unavailable and the wheel is tagged for the exact CPython
that built it. The plain `cmake` build above is unaffected either way; stable-ABI
mode is a wheel-only switch (`-DROSETTA_STABLE_ABI=ON` to force it by hand).)MD";

        // Trailing `, "doc"` for a nanobind call, or empty when there is no doc.
        // (py_lit / qualify_std come from backends/inline/python.hxx.)
        inline std::string nbx_doc_arg(const std::string &doc) {
            return doc.empty() ? std::string{} : ", \"" + py_lit(doc) + "\"";
        }

        // One enum: nb::enum_<E>(m,"E").value("A", E::A)...;
        inline std::string nbx_enum(const GenEnum &e) {
            const std::string eq = qualified_of(e);
            std::string       s = "    nb::enum_<" + eq + ">(m, \"" + exposed_of(e) + "\")";
            for (const auto &v : e.values) {
                s += "\n        .value(\"" + v.name + "\", " + eq + "::" + v.name + ")";
            }
            s += ";\n";
            return s;
        }

        // One field as a chain segment (leading '.', no newline). Mirrors
        // NanobindVisitor::field: readonly -> def_ro; arithmetic + range ->
        // validating def_prop_rw; otherwise def_rw. Member pointers keep the
        // field type implicit, so only the range setter spells a (numeric) type.
        inline std::string nbx_field_segment(const GenClass &k, const GenField &f) {
            const std::string self = qualified_of(k);
            const std::string mp   = "&" + self + "::" + f.name;
            const std::string dq   = nbx_doc_arg(f.doc);
            if (f.is_readonly) {
                return ".def_ro(\"" + f.name + "\", " + mp + dq + ")";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty = f.type.spelling; // arithmetic -> compilable spelling
                const std::string lo = num_str(f.range.min);
                const std::string hi = num_str(f.range.max);
                std::string       s;
                s += ".def_prop_rw(\"" + f.name + "\",\n";
                s += "            [](const " + self + " &s) { return s." + f.name + "; },\n";
                s += "            [](" + self + " &s, " + ty + " v) {\n";
                s += "                if (v < " + lo + " || v > " + hi + ")\n";
                s += "                    throw nb::value_error(\"" + f.name + " out of range [" +
                     lo + ", " + hi + "]\");\n";
                s += "                s." + f.name + " = v;\n";
                s += "            }" + dq + ")";
                return s;
            }
            return ".def_rw(\"" + f.name + "\", " + mp + dq + ")";
        }

        // A sequence-adapted method as a chain segment (see px_seq_method — same
        // adapter, nanobind spelling). nanobind's stl/vector.h caster covers the
        // std::vector boundary.
        inline std::string nbx_seq_method_segment(const GenClass &k, const GenMethod &m,
                                                  const GenContext &c) {
            const PxSeqSig sig = px_seq_sig(m.params, m.param_cpp);
            std::string    decls, call;
            const std::string kq = qualified_of(k);
            if (m.is_extension) {
                decls = kq + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = m.ext_qualified + "(self" + (sig.args.empty() ? "" : ", " + sig.args) +
                       ")";
            } else if (m.is_static) {
                decls = sig.decls;
                call  = kq + "::" + m.name + "(" + sig.args + ")";
            } else {
                decls = kq + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = "self." + m.name + "(" + sig.args + ")";
            }
            std::string body = sig.pre;
            if (is_adapted(m.ret)) {
                body += "        auto &&r = " + call + ";\n";
                body += "        return " + adapt_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                body += "        " + call + ";\n";
            } else {
                body += "        return " + call + ";\n";
            }
            const std::string def = m.is_static ? "def_static" : "def";
            return "." + def + "(\"" + m.name + "\", [](" + decls + ") {\n" + body +
                   "        }" + px_keep_alive(m, c, "nb") + nbx_doc_arg(px_method_doc(m)) +
                   px_arg_list(m.params, "nb", c) + ")";
        }

        // A sequence-typed field as def_prop_ro / def_prop_rw copying through
        // the boundary vector (member pointers would hand nanobind the
        // casterless foreign type).
        inline std::string nbx_seq_field_segment(const GenClass &k, const GenField &f) {
            const std::string vt  = adapt_boundary_cpp(f.type);
            const std::string dq  = nbx_doc_arg(f.doc);
            const std::string get = "[](const " + qualified_of(k) + " &s) { return " +
                                    adapt_from_expr(f.type, "s." + f.name) + "; }";
            if (f.is_readonly) {
                return ".def_prop_ro(\"" + f.name + "\", " + get + dq + ")";
            }
            std::string s;
            s += ".def_prop_rw(\"" + f.name + "\",\n";
            s += "            " + get + ",\n";
            s += "            [](" + qualified_of(k) + " &s, const " + vt + " &v) {\n";
            s += "                s." + f.name + ".resize(v.size());\n";
            s += "                std::copy(v.begin(), v.end(), s." + f.name + ".begin());\n";
            s += "            }" + dq + ")";
            return s;
        }

        // One method as a chain segment. Overloads are already deduped by name in
        // the walk, so &T::m is unambiguous. An extension method binds its free
        // function instead — nanobind, like pybind, treats a free function whose
        // first parameter is T& as an instance method.
        inline std::string nbx_method_segment(const GenClass &k, const GenMethod &m,
                                              const GenContext &c) {
            const std::string dq = nbx_doc_arg(px_method_doc(m));
            const std::string aq = px_arg_list(m.params, "nb", c);
            // Same rules, same reasons as python. px_ref_return: a non-const
            // lvalue-reference return of a bound class binds by reference,
            // since nanobind's automatic policy would copy it.
            // px_borrowed_pointer: a raw pointer to a bound class (or a
            // container of them) binds by reference, since nanobind's automatic
            // policy for a pointer is take_ownership and would DELETE an object
            // the C++ side still owns.
            const std::string policy =
                (px_borrowed_pointer(m.ret, c) || px_ref_return(m, c))
                    ? (m.is_static ? ", nb::rv_policy::reference"
                                   : ", nb::rv_policy::reference_internal")
                    : "";
            // ... and the mirror case: a borrowed pointer handed IN, which the
            // callee may store past the call. nb::keep_alive spelt the same way.
            const std::string ka = px_keep_alive(m, c, "nb");
            if (m.is_extension) {
                return ".def(\"" + m.name + "\", &" + m.ext_qualified + policy + ka + dq + aq +
                       ")";
            }
            const std::string mp = px_member_pointer(k, m);
            if (m.is_static) {
                return ".def_static(\"" + m.name + "\", " + mp + policy + ka + dq + aq + ")";
            }
            return ".def(\"" + m.name + "\", " + mp + policy + ka + dq + aq + ")";
        }

        // The one base class nanobind can be told about, or "" when there is
        // none.
        //
        // Registering the relationship is what makes a derived instance
        // acceptable where a base is expected: without it `nb::class_<Derived>`
        // is an unrelated Python type, and passing one to a method taking
        // `Base *` fails with "incompatible function arguments".
        //
        // Two filters apply, both of them nanobind's:
        //   - a base that is not itself bound is dropped — nanobind resolves it
        //     by looking the type up in the module.
        //   - at most ONE base survives. nb::class_<T, Ts...> pulls a single
        //     `Base` out of Ts and static_asserts that nothing else is left
        //     over ("invoked with extra arguments that could not be handled"):
        //     nanobind has no multiple inheritance, where pybind11 and sol2 do.
        //     A second bound base is reported and dropped rather than emitted
        //     into code that cannot compile.
        inline std::string nb_bound_base(const GenClass &k, const GenContext &c) {
            auto index_of = [&](const std::string &q) -> std::size_t {
                for (std::size_t i = 0; i < c.classes.size(); ++i) {
                    // A class with a non-public destructor is in the IR but
                    // never emitted (see the is_destructible guard below), so it
                    // is no more registered than an unlisted type — naming it as
                    // a base would break the import.
                    if (qualified_of(c.classes[i]) == q && c.classes[i].is_destructible) {
                        return i;
                    }
                }
                return c.classes.size(); // not bound
            };
            const std::size_t self = index_of(qualified_of(k));

            std::string first;
            std::string dropped;
            for (const auto &b : k.bases) {
                const std::size_t at = index_of(b);
                if (at == c.classes.size()) {
                    continue; // base not bound — nothing to point nanobind at
                }
                if (first.empty()) {
                    first = b;
                    // nanobind binds in emission order and needs the base type
                    // already registered when the derived class declares it.
                    // Emission follows manifest order, so this is the user's to
                    // fix: flag it here rather than at import time.
                    if (at > self) {
                        std::fprintf(stderr,
                                     "rosetta::nanobind: class '%s' is bound before its base "
                                     "'%s' — list the base first in the manifest, or the module "
                                     "will fail to import\n",
                                     k.name.c_str(), b.c_str());
                    }
                } else {
                    dropped += (dropped.empty() ? "" : ", ") + b;
                }
            }
            if (!dropped.empty()) {
                std::fprintf(stderr,
                             "rosetta::nanobind: class '%s' has several bound bases — kept '%s', "
                             "dropped %s (nanobind has no multiple inheritance)\n",
                             k.name.c_str(), first.c_str(), dropped.c_str());
            }
            return first;
        }

        inline std::string nbx_class(const GenClass &k, const GenContext &c) {
            // A class whose destructor is not public cannot be wrapped: every
            // runtime backend destroys what it holds. Skip it with a note —
            // the alternative is a compile error inside the framework headers.
            if (!k.is_destructible) {
                std::fprintf(stderr,
                             "rosetta::%s: class '%s' has a non-public destructor "
                             "(ref-counted?) — skipped\n",
                             "nanobind", k.name.c_str());
                return {};
            }

            std::vector<std::string> segs;

            // No constructor for an abstract class: nb::init<> instantiates the
            // Alias type (== T when no trampoline is emitted, which is always
            // here), so `new T{}` on a pure-virtual interface is ill-formed.
            // The walk still records the implicitly-declared default ctor of
            // such a class, so the guard belongs on the loop, not only on the
            // is_default_constructible fallback. Same rule as the wasm / lua /
            // julia expanded backends.
            bool saw_default = false;
            for (std::size_t i = 0; !k.is_abstract && i < k.ctor_param_cpp.size(); ++i) {
                const auto &params = k.ctor_param_cpp[i];
                if (params.empty()) {
                    saw_default = true;
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    args += (j ? ", " : "") + qualify_std(params[j]);
                }
                segs.push_back(".def(nb::init<" + args + ">())");
            }
            if (!saw_default && !k.is_abstract && k.is_default_constructible) {
                segs.push_back(".def(nb::init<>())");
            }
            for (const auto &f : k.fields) {
                if (is_adapted(f.type)) {
                    if (adapt_ok(f.type)) {
                        segs.push_back(nbx_seq_field_segment(k, f));
                    }
                    continue; // never hand nanobind the casterless foreign type
                }
                if (!px_field_ok(f, c)) {
                    continue; // non-copyable member object (shared pybind gate)
                }
                segs.push_back(nbx_field_segment(k, f));
            }
            for (const auto &m : k.methods) {
                if (px_touches(m)) {
                    if (seq_adaptable(m) && px_seq_rest_ok(m, c)) {
                        segs.push_back(nbx_seq_method_segment(k, m, c));
                        coverage::note_bound("nanobind", k, m);
                    } else {
                        coverage::note_skip("nanobind", k, m, "sequence_not_adaptable",
                                            "a registered sequence in the signature has no "
                                            "std::vector boundary adapter for this backend");
                    }
                    continue; // adapter or nothing (see px_seq_method)
                }
                // Every overload binds. nanobind, like pybind11, collects
                // repeated .def("name", …) into one overload set and dispatches
                // on the argument types; the ambiguity is only in the C++ member
                // pointer, which px_member_pointer casts away. (This backend used
                // to skip overload sets outright, because it spelled the bare
                // `&T::name` and could not have compiled one.)
                if (!px_method_ok(m, c)) {
                    coverage::note_skip("nanobind", k, m, "unmarshalable_signature",
                                        px_skip_reason(m, c));
                    continue; // signature the emitted line could not compile
                }
                segs.push_back(nbx_method_segment(k, m, c));
                coverage::note_bound("nanobind", k, m);
            }

            // Trailing template argument: the bound base, so a derived instance
            // is accepted where the base is expected (nb_bound_base explains
            // why there is at most one).
            const std::string base = nb_bound_base(k, c);
            std::string       s    = "    nb::class_<" + qualified_of(k) +
                            (base.empty() ? "" : ", " + base) + ">(m, \"" + exposed_of(k) + "\")";
            for (const auto &seg : segs) {
                s += "\n        " + seg;
            }
            s += ";\n";
            return s;
        }

        inline std::string nanobind_expanded_source(const GenContext &c0) {
            // Same rule as python: where nanobind has the caster for
            // the owning library, a dual-marked type (registered sequence +
            // interop) binds as numpy rather than through the copy adapter.
            const GenContext c = interop_wins(c0, px_interop_caster);
            std::string      body;
            for (const auto &e : c.enums) {
                body += nbx_enum(e);
            }
            for (const auto &k : c.classes) {
                body += nbx_class(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe; // free functions go through the same gates
                probe.ret    = f.ret;
                probe.params = f.params;
                if (px_touches(probe)) {
                    if (seq_adaptable(probe) && px_seq_rest_ok(probe, c)) {
                        const PxSeqSig    sig  = px_seq_sig(f.params, {});
                        const std::string call = fn_call_expr(f) + "(" + sig.args + ")";
                        std::string       fb   = sig.pre;
                        if (is_adapted(f.ret)) {
                            fb += "        auto &&r = " + call + ";\n";
                            fb += "        return " + adapt_from_expr(f.ret, "r") + ";\n";
                        } else if (f.ret.kind == "void") {
                            fb += "        " + call + ";\n";
                        } else {
                            fb += "        return " + call + ";\n";
                        }
                        body += "    m.def(\"" + f.name + "\", [](" + sig.decls + ") {\n" + fb +
                                "    }" + nbx_doc_arg(px_method_doc(f)) +
                                px_arg_list(f.params, "nb", c) + ");\n";
                        coverage::note_bound_function("nanobind", f);
                    } else {
                        coverage::note_skip_function("nanobind", f, "sequence_not_adaptable",
                                                     "a registered sequence in the signature has "
                                                     "no std::vector boundary adapter");
                    }
                    continue;
                }
                if (!px_method_ok(probe, c)) {
                    coverage::note_skip_function("nanobind", f, "unmarshalable_signature",
                                                 "no nanobind type-caster for a type in this "
                                                 "signature");
                    continue;
                }
                body += "    m.def(\"" + f.name + "\", " + fn_addr(f) +
                        nbx_doc_arg(px_method_doc(f)) + px_arg_list(f.params, "nb", c) + ");\n";
                coverage::note_bound_function("nanobind", f);
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            // nanobind splits its casters one per header, where pybind11 ships
            // them all in <pybind11/stl.h>. Pull the same coverage the
            // python backend gets for free, plus the smart pointers
            // (pybind11 handles those in its core): without the matching
            // header a bound signature still COMPILES and then throws
            // "Unable to convert function return value to a Python type" at
            // call time — e.g. a factory returning std::shared_ptr<Iface>, a
            // std::variant field, or a std::map<std::string, std::string>
            // options argument. Each header only defines type casters, so the
            // ones a module never exercises cost nothing.
            out += "#include <nanobind/nanobind.h>\n";
            out += "#include <nanobind/stl/string.h>\n";
            out += "#include <nanobind/stl/vector.h>\n";
            out += "#include <nanobind/stl/filesystem.h>\n";
            out += "#include <nanobind/stl/function.h>\n";
            out += "#include <nanobind/stl/shared_ptr.h>\n";
            out += "#include <nanobind/stl/unique_ptr.h>\n";
            out += "#include <nanobind/stl/variant.h>\n";
            out += "#include <nanobind/stl/optional.h>\n";
            out += "#include <nanobind/stl/pair.h>\n";
            out += "#include <nanobind/stl/tuple.h>\n";
            out += "#include <nanobind/stl/array.h>\n";
            out += "#include <nanobind/stl/map.h>\n";
            out += "#include <nanobind/stl/unordered_map.h>\n";
            out += "#include <nanobind/stl/set.h>\n";
            out += "#include <nanobind/stl/unordered_set.h>\n";
            out += "#include <algorithm>\n";
            out += "#include <filesystem>\n";
            out += "#include <vector>\n";
            // Caster headers for the opted-in foreign libraries (manifest
            // "interop"). nanobind splits these per library exactly as it
            // splits the STL casters, and the failure mode is the same one:
            // without the header the binding compiles and throws at call time.
            // px_interop_caster() gates the IR side for both python-family
            // backends, so this list must cover every name it admits.
            for (const auto &n : c.interop) {
                if (n == "eigen") {
                    // Dense Eigen types to / from numpy. nanobind also ships
                    // <nanobind/eigen/sparse.h>; it is not emitted, because a
                    // sparse type in a bound signature is rare enough that
                    // paying its compile time by default is the wrong trade.
                    out += "#include <nanobind/eigen/dense.h>\n";
                }
            }
            auto add = [&](const std::string &h) { append_include(out, h); };
            out += init_includes(c);
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += "\nnamespace nb = nanobind;\n";
            out += "\nNB_MODULE(" + c.lib + ", m) {\n";
            out += init_block(c);
            out += "    m.doc() = \"Auto-generated (expanded) nanobind bindings for " + c.lib +
                   ".\";\n";
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string Nanobind::render(const GenContext &c) const {
            return nanobind_expanded_source(c);
        }

        inline void Nanobind::emit(const GenContext &c) const {
            auto dir = c.out_dir / "nanobind";
            write_file(dir / "auto_nanobind.cpp", nanobind_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(NANOBINDX_CMAKE, c));
            // Wheel packaging. The builder script and the README's packaging
            // section are shared verbatim with python (both come from
            // backends/inline/python.hxx); only pyproject.toml and the ABI
            // note are nanobind's own.
            write_file(dir / "pyproject.toml", render_meta(NANOBINDX_PYPROJECT, c));
            write_script(dir / "make_wheel.py",
                         subst(PYX_MAKE_WHEEL,
                               {{"LIB", c.lib}, {"USER_LIB_DIRS", py_dir_list(c)}}));
            write_file(dir / "README.md",
                       readme("nanobind", c,
                              subst(NANOBINDX_README_BUILD, {{"LIB", c.lib}}) + "\n\n" +
                                  subst(PYX_README_WHEEL, {{"ABI_NOTE", NANOBINDX_ABI_NOTE}})));
        }

    } // namespace backend
} // namespace rosetta
