// Copyright (c) fmaerten@gmail.com
// License: MIT

// Expanded (reflection-free) pybind11 backend. Included by inline/generate.hxx
// after backends/python.h, whose virtual_methods()/trampolines_of() helpers it
// reuses, and after the shared render helpers (subst / num_str / write_file).

#pragma once

namespace rosetta {
    namespace backend {
        using namespace gen_detail; // shared render / IR helpers

        // A stock-toolchain CMake: C++17, pybind11, the user's include dir only.
        // No clang-p2996, no -freflection/-fannotation-attributes, no -nostdlib++.
        constexpr std::string_view PYX_CMAKE =
            R"CMK(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# These bindings are plain pybind11: NO C++26, NO reflection, NO rosetta headers.
cmake_minimum_required(VERSION 3.18)
project({{LIB}}_binding CXX)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON){{BUILD_CONFIG}}

execute_process(
    COMMAND {{PYTHON_CMD}} -c "import sys; print(sys.executable)"
    OUTPUT_VARIABLE Python_EXECUTABLE
    OUTPUT_STRIP_TRAILING_WHITESPACE)
set(Python3_EXECUTABLE "${Python_EXECUTABLE}" CACHE FILEPATH "" FORCE)
set(PYBIND11_FINDPYTHON ON)

# Prefer an installed pybind11 (pip), fall back to fetching a pinned release.
if(NOT pybind11_DIR)
    execute_process(
        COMMAND ${Python_EXECUTABLE} -m pybind11 --cmakedir
        OUTPUT_VARIABLE pybind11_DIR
        RESULT_VARIABLE _pybind11_probe
        ERROR_QUIET
        OUTPUT_STRIP_TRAILING_WHITESPACE)
    if(NOT _pybind11_probe EQUAL 0)
        set(pybind11_DIR "")
    endif()
endif()
if(pybind11_DIR)
    find_package(pybind11 REQUIRED CONFIG)
else()
    include(FetchContent)
    FetchContent_Declare(
        pybind11
        GIT_REPOSITORY https://github.com/pybind/pybind11.git
        GIT_TAG v3.0.4)
    FetchContent_MakeAvailable(pybind11)
endif()

pybind11_add_module({{LIB}} NO_EXTRAS auto_pybind.cpp)

# Only the user's headers — rosetta's include dir is deliberately absent.
target_include_directories({{LIB}} PRIVATE
    {{USER_INCLUDE}})

{{USER_LIB_BLOCK}}

# Wheel builds (scikit-build-core sets SKBUILD) package what CMake *installs*,
# so the module must be installed at the wheel root for `import {{LIB}}` to work.
install(TARGETS {{LIB}} LIBRARY DESTINATION . RUNTIME DESTINATION .)

# Convenience for the in-tree build only: drop the module next to the sources so
# it can be imported from this directory. Skipped under SKBUILD, whose build tree
# is a throw-away temp copy.
if(NOT SKBUILD)
    add_custom_command(TARGET {{LIB}} POST_BUILD
        COMMAND ${CMAKE_COMMAND} -E copy
            $<TARGET_FILE:{{LIB}}>
            ${CMAKE_CURRENT_SOURCE_DIR}/$<TARGET_FILE_NAME:{{LIB}}>)
endif()
{{OUT_DIR_BLOCK}}
)CMK";

        // pyproject.toml driving the wheel build. scikit-build-core runs the
        // CMakeLists above unchanged, so there is no second build description
        // to keep in sync — the wheel and the plain `cmake -S . -B build` build
        // compile the very same target the very same way.
        //
        // pybind11 has no stable-ABI mode, so every wheel is tagged for the
        // exact CPython that built it (cp312-cp312-...). Building for several
        // interpreters means running the builder once per interpreter — see
        // make_wheel.sh. (The nanobind backend can do better; it emits an abi3
        // wheel on 3.12+.)
        constexpr std::string_view PYX_PYPROJECT =
            R"TOML(# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
# Wheel build: `./make_wheel.sh`, or `python3 -m build --wheel`.
[build-system]
requires = ["scikit-build-core>=0.10", "pybind11>=2.12"]
build-backend = "scikit_build_core.build"

[project]
name = "{{LIB}}"
version = "{{VERSION}}"
description = "Auto-generated pybind11 bindings for {{LIB}}."
requires-python = "{{REQUIRES_PYTHON}}"

[tool.scikit-build]
cmake.version = ">=3.18"
cmake.build-type = "Release"
# The extension module is installed at the wheel root by CMake's install() —
# there is no Python package directory to copy alongside it.
wheel.packages = []
sdist.include = ["auto_pybind.cpp", "CMakeLists.txt"]
)TOML";

        // Build/Use section for the generated README — kept next to PYX_CMAKE
        // so the doc can't drift from the template it describes. Unlike the
        // thin python backend the source is pre-expanded: plain C++17 pybind11,
        // any stock compiler, no clang-p2996 and no rosetta headers.
        constexpr std::string_view PYX_README_BUILD = R"MD(## Build

The emitted source is plain C++17 pybind11 — any stock compiler works; no
reflection toolchain, no rosetta headers. pybind11 is taken from an installed
copy when available (`pip install pybind11`); otherwise CMake fetches a pinned
release at configure time (network access needed on the first configure).

```sh
cmake -S . -B build && cmake --build build
```

## Use

A post-build step copies the module next to the sources, so from this directory:

```sh
python3 -c "import {{LIB}}"
```)MD";

        // The manifest's user_lib directories, de-duplicated, as a Python list
        // literal for the wheel script. Emitted as ordinary (non-raw) strings
        // with backslashes and quotes escaped, so a Windows path survives —
        // a raw literal would be prettier but cannot end in a backslash.
        inline std::string py_dir_list(const GenContext &c) {
            std::vector<std::string> dirs;
            for (const auto &u : c.user_libs) {
                if (!u.dir.empty() &&
                    std::find(dirs.begin(), dirs.end(), u.dir) == dirs.end()) {
                    dirs.push_back(u.dir);
                }
            }
            if (dirs.empty()) {
                return "[]";
            }
            std::string s = "[\n";
            for (const auto &d : dirs) {
                s += "    \"";
                for (char ch : d) {
                    if (ch == '\\' || ch == '"') {
                        s += '\\';
                    }
                    s += ch;
                }
                s += "\",\n";
            }
            s += "]";
            return s;
        }

        // Wheel builder. Python, not sh: building a wheel already requires an
        // interpreter (`python -m build` is the entry point), so a .py script
        // adds no dependency that isn't mandatory anyway — while sh would rule
        // out Windows, the one platform these stock-toolchain backends exist to
        // reach. It also lets the interpreter running the script BE the one the
        // wheel is built for (sys.executable), instead of an env-var convention.
        //
        // Shared verbatim by the nanobind backend (which includes this header),
        // so it stays source-file agnostic: everything about *what* to build is
        // in pyproject.toml.
        //
        // The repair step is not optional when the manifest declares a
        // "user_lib": the CMake links those by absolute path out of the
        // manifest's `dir`, so the freshly built module refers to a directory
        // that does not exist on the installing machine. Each platform has its
        // own tool — delocate (macOS), auditwheel (Linux), delvewheel (Windows)
        // — and Windows needs the extra hand: a .pyd records no search path for
        // its DLLs (there is no rpath), so delvewheel cannot discover them the
        // way the other two follow a Mach-O / ELF load command. Hence
        // USER_LIB_DIRS, baked in from the manifest at generation time. On Linux
        // repair also retags the wheel manylinux_* — a raw linux_x86_64 wheel is
        // one PyPI refuses. Failure is a warning, not an error: a wheel with
        // nothing external to bundle is already correct, and auditwheel
        // legitimately declines to certify a host whose glibc is newer than
        // every manylinux profile.
        constexpr std::string_view PYX_MAKE_WHEEL =
            R"PY(#!/usr/bin/env python3
# Generated by rosetta::generate (expanded, reflection-free) — do not edit by hand.
"""Build a binary wheel for `{{LIB}}` from this directory.

    python make_wheel.py                    # wheel for the interpreter running this
    python3.11 make_wheel.py                # wheel for a specific interpreter
    python make_wheel.py --outdir /tmp/whl  # somewhere other than ./dist
    python make_wheel.py --no-repair        # skip the bundling / retagging step

--outdir may be shared with other projects (`rosetta_gen --build --wheel-dir`
collects every backend's wheels in one place); only the wheels this run produces
are repaired.

Runs on Linux, macOS and Windows alike — the wheel is built by scikit-build-core,
which drives the CMakeLists.txt next to this script, so it compiles the same
target with the same flags as a plain `cmake --build`.

The wheel is always built for the interpreter that RUNS this script; covering
several Python versions means running it once per interpreter. For a matrix of
versions and platforms in one go, use cibuildwheel instead:

    pipx run cibuildwheel --platform auto
"""

import argparse
import glob
import os
import subprocess
import sys

# Directories holding the external libraries the bindings link against (manifest
# "user_lib"), resolved at generation time. Windows needs them spelled out: a
# .pyd records no search path for its DLLs, so delvewheel cannot discover them
# the way delocate / auditwheel follow a Mach-O / ELF load command.
USER_LIB_DIRS = {{USER_LIB_DIRS}}


def run(cmd, fatal=True):
    """Run a command, echoing it first. Returns its exit code."""
    print(">>> " + " ".join(cmd), flush=True)
    rc = subprocess.call(cmd)
    if rc != 0 and fatal:
        sys.exit(rc)
    return rc


def wheels_in(outdir):
    """Map of wheel path -> mtime, for spotting which ones a build produced."""
    found = {}
    for whl in glob.glob(os.path.join(outdir, "*.whl")):
        try:
            found[whl] = os.path.getmtime(whl)
        except OSError:
            pass
    return found


def repair(outdir, wheels):
    """Bundle external shared libraries into `wheels` and fix the platform tag.

    Repaired copies land in <outdir>/repaired. Returns 0 on success. Only the
    wheels this run produced are passed in — several projects may share one
    --outdir, and re-repairing a neighbour's wheel is at best wasted work.
    """
    if not wheels:
        print(">>> no wheel produced in %s — nothing to repair" % outdir)
        return 1

    py = sys.executable
    dest = os.path.join(outdir, "repaired")

    if sys.platform == "darwin":
        tool = "delocate"
        argv = lambda whl: [py, "-m", "delocate.cmd.delocate_wheel", "-w", dest, "-v", whl]
    elif sys.platform.startswith("linux"):
        tool = "auditwheel"
        argv = lambda whl: [py, "-m", "auditwheel", "repair", "-w", dest, whl]
    elif sys.platform == "win32":
        tool = "delvewheel"
        # --add-path takes ONE os.pathsep-separated list, not a repeated flag.
        extra = ["--add-path", os.pathsep.join(USER_LIB_DIRS)] if USER_LIB_DIRS else []
        argv = lambda whl: [py, "-m", "delvewheel", "repair", "-w", dest, whl] + extra
    else:
        print(">>> no wheel-repair tool known for %s — skipped" % sys.platform)
        return 0

    if run([py, "-m", "pip", "install", "--quiet", "--upgrade", tool], fatal=False) != 0:
        return 1

    rc = 0
    for whl in wheels:
        if run(argv(whl), fatal=False) != 0:
            rc = 1
    return rc


def main():
    parser = argparse.ArgumentParser(
        description="Build a binary wheel for {{LIB}}.")
    parser.add_argument("--outdir", default="dist", metavar="DIR",
                        help="where to write the wheel (default: dist)")
    parser.add_argument("--no-repair", action="store_true",
                        help="skip bundling external libraries / retagging")
    args = parser.parse_args()

    # Always build from the directory holding this script, whatever the cwd.
    os.chdir(os.path.dirname(os.path.abspath(__file__)))

    py = sys.executable
    print(">>> building {{LIB}} wheel with Python %s (%s)"
          % (sys.version.split()[0], py), flush=True)
    run([py, "-m", "pip", "install", "--quiet", "--upgrade", "build"])

    # Snapshot first, so the repair step below touches only what THIS run built.
    # --outdir may be shared (rosetta_gen --build --wheel-dir collects every
    # backend's wheels in one place), and a rebuild reuses the same filename —
    # hence comparing mtimes rather than just the set of paths.
    before = wheels_in(args.outdir)
    run([py, "-m", "build", "--wheel", "--outdir", args.outdir, "."])
    built = sorted(path for path, mtime in wheels_in(args.outdir).items()
                   if before.get(path) != mtime)

    if args.no_repair:
        print(">>> wheels in %s (repair skipped)" % args.outdir)
        return 0

    if repair(args.outdir, built) == 0:
        print(">>> wheels in %s (redistributable copies, if any, in %s)"
              % (args.outdir, os.path.join(args.outdir, "repaired")))
        return 0

    print(">>> WARNING: wheel repair failed — the wheel in %s is usable on THIS"
          % args.outdir)
    print(">>>          machine but may not be redistributable (external shared")
    print(">>>          libraries not bundled, or platform tag not certified).")
    return 0


if __name__ == "__main__":
    sys.exit(main())
)PY";

        // Packaging section for the generated README. Shared verbatim by the
        // nanobind backend; {{ABI_NOTE}} is the one part that differs (nanobind
        // can emit a single abi3 wheel on 3.12+, pybind11 cannot).
        constexpr std::string_view PYX_README_WHEEL = R"MD(## Package (wheel)

`pyproject.toml` and `make_wheel.py` build a redistributable wheel from exactly
the same CMake target as above — scikit-build-core drives this CMakeLists.txt,
so there is no second build description to keep in sync.

```sh
python make_wheel.py                    # -> dist/*.whl
python3.11 make_wheel.py                # a specific interpreter
python make_wheel.py --outdir /tmp/whl  # somewhere other than ./dist
```

The builder is Python, not a shell script, so it runs on Linux, macOS and
Windows alike — building a wheel needs an interpreter anyway. The wheel is built
for whichever interpreter runs the script.

{{ABI_NOTE}}

The script then repairs the result with `delocate` (macOS), `auditwheel` (Linux)
or `delvewheel` (Windows). That step matters when the manifest declares a
`user_lib`: the module links those libraries by absolute path, so they must be
copied *into* the wheel before it can be installed anywhere else. Repaired
wheels land in `dist/repaired`. On Linux it also retags the wheel `manylinux_*`,
without which PyPI rejects it. On Windows the `user_lib` directories are baked
into the script as `USER_LIB_DIRS` and passed to `delvewheel --add-path`: a
`.pyd` records no search path for its DLLs, so unlike the other two tools
delvewheel cannot find them on its own.

The version comes from the manifest's `"version"` field; edit it there and
re-run the generator rather than editing `pyproject.toml`.

Note that only the *wheel* is redistributable. An sdist built from this
directory is not: the CMakeLists.txt points at the header and library paths the
manifest resolved on the generating machine, which do not exist elsewhere.
Ship wheels, or re-run the generator wherever you build.

For a matrix of Python versions and platforms in one go, use cibuildwheel:

```sh
pipx run cibuildwheel --platform auto
```)MD";

        // {{ABI_NOTE}} for the pybind11 flavour: no stable ABI, one wheel per
        // interpreter.
        constexpr std::string_view PYX_ABI_NOTE =
            R"MD(pybind11 has no stable-ABI mode, so each wheel is tagged for the exact CPython
that built it (`cp312-cp312-...`) — covering several versions means running the
script once per interpreter.)MD";

        // Escape a docstring for a C++ string literal.
        //
        // Line breaks matter here. This used to escape backslashes and quotes
        // only, which held while every docstring came from a `doc{"..."}`
        // annotation — those are single-line by construction, since the source
        // of one is itself a C++ string literal. A docstring harvested from a
        // header is not: a `/** ... */` block spans paragraphs, and a raw
        // newline inside a "..." literal does not compile. Everything that can
        // end or confuse the literal is spelled out.
        //
        // Shared by the nanobind, imgui and qt emitters as well as this one.
        inline std::string py_lit(const std::string &s) {
            std::string out;
            for (unsigned char ch : s) {
                switch (ch) {
                case '\\': out += "\\\\"; break;
                case '"':  out += "\\\""; break;
                case '\n': out += "\\n";  break;
                case '\r': out += "\\r";  break;
                case '\t': out += "\\t";  break;
                default:
                    if (ch < 0x20 || ch == 0x7f) {
                        char buf[8];
                        std::snprintf(buf, sizeof buf, "\\x%02x", ch);
                        out += buf;
                        // Hex escapes are greedy: close and reopen the literal
                        // so a following hex digit is not swallowed into it.
                        out += "\"\"";
                    } else {
                        out += static_cast<char>(ch); // UTF-8 passes through
                    }
                    break;
                }
            }
            return out;
        }

        // Trailing `, "doc"` for a pybind call, or empty when there is no doc.
        inline std::string doc_arg(const std::string &doc) {
            return doc.empty() ? std::string{} : ", \"" + py_lit(doc) + "\"";
        }

        // The docstring pybind/nanobind attach to a method, with the parameter
        // and return documentation folded in. Python has no structured place for
        // either — `help()` prints the docstring — so the convention every hand
        // written binding follows is a section per argument, which is what this
        // renders. `py::arg` still carries the NAMES; this carries their prose.
        inline std::string px_method_doc(const GenMethod &m) {
            std::string out = m.doc;
            bool        any = false;
            for (const auto &p : m.params) {
                any = any || (!p.doc.empty() && !is_out_param(p));
            }
            if (any) {
                out += out.empty() ? "" : "\n\n";
                out += "Args:";
                for (const auto &p : m.params) {
                    if (p.doc.empty() || is_out_param(p)) {
                        continue;
                    }
                    out += "\n    " + p.name + ": " + p.doc;
                }
            }
            if (!m.returns.empty()) {
                out += out.empty() ? "" : "\n\n";
                out += "Returns:\n    " + m.returns;
            }
            return out;
        }

        // Same, for a free function: GenFunction carries the same doc / returns
        // / per-parameter text, and Python has the same one place to put it.
        inline std::string px_method_doc(const GenFunction &f) {
            GenMethod probe;
            probe.doc     = f.doc;
            probe.returns = f.returns;
            probe.params  = f.params;
            return px_method_doc(probe);
        }

        // The `, py::arg("x"), py::arg("n") = 32` tail that turns a positional
        // binding into a keyword-argument one. `ns` is "py" or "nb" — the two
        // frameworks spell the annotation identically otherwise.
        //
        // Two rules keep this from producing a module that fails to import:
        //
        //  - the list is ALL or NOTHING. pybind11 requires exactly one arg
        //    annotation per parameter (self excluded, which it accounts for
        //    itself through is_method), so a partial list is a static_assert.
        //    Out-parameters are not parameters of the emitted callable — the
        //    adapter declares them as locals — so they are excluded here too,
        //    matching px_seq_sig.
        //  - defaults are applied only along the TRAILING run of parameters
        //    whose spelling was actually recovered. A default may be missing
        //    from the middle of the list (the harvester declines an expression
        //    it cannot re-emit safely), and "a default followed by a
        //    non-default" is rejected at import time.
        //
        // Nothing is emitted at all when no parameter has a real name or a
        // default: `py::arg("arg0")` promises a keyword nobody wants to type.
        //
        // May a default of this TYPE be spelled at all? pybind converts an
        // `arg` default into a Python object AT MODULE IMPORT, before any call —
        // so a default whose type is not registered yet does not degrade, it
        // throws `arg(): could not convert default argument` and the whole
        // module fails to import. Scalars and strings are always convertible.
        // An enum is convertible only once bound, which holds for an enum in
        // this module because both emitters register enums ahead of classes;
        // an enum the manifest did not bind, and every class type, is refused.
        inline bool px_default_ok(const GenType &t, const GenContext &c) {
            if (t.kind == "number" || t.kind == "boolean" || t.kind == "string") {
                return true;
            }
            if (t.kind != "enum") {
                return false;
            }
            for (const auto &e : c.enums) {
                const bool match = t.object_qualified.empty()
                                       ? (e.name == t.object)
                                       : (qualified_of(e) == t.object_qualified);
                if (match) {
                    return true;
                }
            }
            return false;
        }

        inline std::string px_arg_list(const std::vector<GenParam> &params, const char *ns,
                                       const GenContext &c) {
            std::vector<const GenParam *> kept;
            for (const auto &p : params) {
                if (!is_out_param(p)) {
                    kept.push_back(&p);
                }
            }
            if (kept.empty()) {
                return {};
            }
            bool worth = false;
            for (std::size_t i = 0; i < kept.size(); ++i) {
                worth = worth || !kept[i]->default_text.empty() ||
                        kept[i]->name != "arg" + std::to_string(i);
            }
            if (!worth) {
                return {};
            }
            std::vector<bool> with_default(kept.size(), false);
            for (std::size_t i = kept.size(); i-- > 0;) {
                if (kept[i]->default_text.empty() || !px_default_ok(kept[i]->type, c)) {
                    break;
                }
                with_default[i] = true;
            }
            std::string out;
            for (std::size_t i = 0; i < kept.size(); ++i) {
                out += ", " + std::string(ns) + "::arg(\"" + kept[i]->name + "\")";
                if (with_default[i]) {
                    out += " = " + kept[i]->default_text;
                }
            }
            return out;
        }

        // Re-qualify standard-library names in an exact type spelling. The
        // p2996 fork's display_string_of prints library types unqualified
        // (`vector<double, allocator<double>>`); a stock compiler needs the
        // `std::`. We word-match a known set of std identifiers and prepend
        // `std::` when the occurrence is a standalone token not already
        // qualified. Only constructor parameter types are spelled out in the
        // emitted code (fields/methods go through member pointers, which keep
        // types implicit), so this is the single place qualification is needed.
        inline std::string qualify_std(std::string s) {
            static constexpr std::string_view names[] = {
                "basic_string", "string_view", "string",  "wstring",     "vector",
                "allocator",    "char_traits", "function", "shared_ptr",  "unique_ptr",
                "unordered_map","unordered_set","map",     "multimap",    "set",
                "multiset",     "pair",        "tuple",    "array",       "list",
                "deque",        "optional",    "variant",  "hash",        "less",
                "equal_to",     "size_t",      "ptrdiff_t","initializer_list"};
            auto ident_char = [](char ch) {
                return (ch >= 'a' && ch <= 'z') || (ch >= 'A' && ch <= 'Z') ||
                       (ch >= '0' && ch <= '9') || ch == '_';
            };
            for (std::string_view nm : names) {
                std::string::size_type pos = 0;
                while ((pos = s.find(nm, pos)) != std::string::npos) {
                    const bool left_ok =
                        pos == 0 || (!ident_char(s[pos - 1]) && s[pos - 1] != ':');
                    const std::string::size_type end = pos + nm.size();
                    const bool right_ok = end >= s.size() || !ident_char(s[end]);
                    if (left_ok && right_ok) {
                        s.insert(pos, "std::");
                        pos = end + 5; // past the inserted "std::" + name
                    } else {
                        pos = end;
                    }
                }
            }
            return s;
        }

        // Does pybind11 ship a caster for this foreign library? The single
        // source of truth for both halves of the feature — the gate that lets
        // its types through (px_marshalable) and the header that makes that
        // true (px_interop_includes). A library rosetta knows but pybind11 has
        // no caster for stays skipped, which is the honest outcome.
        // ---- pybind11 trampolines -------------------------------------------
        // Lived in the thin python backend until it was removed; kept here
        // because BOTH this backend and node emit trampolines from
        // the same virtual_spec the walk records.
        // The instance virtual methods of a class — the ones a trampoline must
        // shim. Empty result ⇒ no trampoline (and a plain py::class_<T> binding).
        // A "final" class (manifest flag) never gets a trampoline: its virtuals
        // bind as ordinary methods only.
        inline std::vector<const GenMethod *> virtual_methods(const GenClass &k) {
            std::vector<const GenMethod *> out;
            if (k.is_final) {
                return out;
            }
            for (const auto &m : k.methods) {
                if (m.is_virtual && !m.is_static) {
                    out.push_back(&m);
                }
            }
            return out;
        }

        // One trampoline class: `class Py_T : public T { using T::T; <override per
        // virtual> };`. Each override reproduces the base signature exactly
        // (cv/ref/noexcept) — otherwise it would hide rather than override — and
        // routes through PYBIND11_OVERRIDE[_PURE] so a Python subclass can take over.
        // Named after the EXPOSED name (unique across the module) and derived
        // from the QUALIFIED spelling, so two bound classes sharing an
        // unqualified identifier (the "expose" rename case) coexist in one TU.
        inline std::string trampoline_for(const GenClass &k) {
            const auto virts = virtual_methods(k);
            if (virts.empty()) {
                return {};
            }
            const std::string kq = qualified_of(k);
            std::string s = "class Py_" + exposed_of(k) + " : public " + kq + " {\npublic:\n";
            s += "    using " + kq + "::" + k.name + ";\n";
            for (const GenMethod *m : virts) {
                // A virtual whose signature pybind11 can't cast (e.g. a pointer to an
                // incomplete type) would make PYBIND11_OVERRIDE fail to compile. Skip
                // its override: a concrete bound class already supplies the body, so
                // the trampoline stays instantiable; Python just can't override it.
                if (!m->sig_bindable) {
                    continue;
                }
                // Exact spellings re-qualified per the IR: an unqualified user
                // token ("Data &") is ambiguous once two bound namespaces
                // declare it (see qualify_objects).
                const std::string rq  = qualify_objects(m->ret_cpp, m->ret);
                std::string sig = "    " + rq + " " + m->name + "(";
                std::string fwd; // forwarded argument names for the macro
                for (std::size_t i = 0; i < m->param_cpp.size(); ++i) {
                    const std::string pn = "p" + std::to_string(i);
                    std::string       pt = m->param_cpp[i];
                    if (i < m->params.size()) {
                        pt = qualify_objects(std::move(pt), m->params[i].type);
                    }
                    sig += (i ? ", " : "") + pt + " " + pn;
                    fwd += (i ? ", " : "") + pn;
                }
                sig += ")";
                if (m->is_const) {
                    sig += " const";
                }
                if (m->is_noexcept) {
                    sig += " noexcept";
                }
                sig += " override {\n";
                // PYBIND11_OVERRIDE[_PURE] is a macro, so a return type carrying
                // a comma — which every std container spelling does, e.g. the
                // `vector<T, allocator<T>>` display_string_of produces — gets
                // split by the PREPROCESSOR across two macro arguments, shifting
                // the class and method arguments along with it. The errors that
                // follow name types nobody wrote (`vector<T, _object *>`). Hide
                // the comma behind a local alias, and only when there is one, so
                // the output for every other override stays byte-identical. The
                // return type is the one place this can bite: the forwarded
                // argument names are plain identifiers.
                std::string ret_tok = rq;
                if (rq.find(',') != std::string::npos) {
                    ret_tok = "rosetta_ret_t";
                    sig += "        using " + ret_tok + " = " + rq + ";\n";
                }
                sig += std::string("        ") +
                       (m->is_pure ? "PYBIND11_OVERRIDE_PURE(" : "PYBIND11_OVERRIDE(") + ret_tok +
                       ", " + kq + ", " + m->name + ", " + fwd + ");\n    }\n";
                s += sig;
            }
            s += "};\n";
            return s;
        }

        // All trampoline classes for the context, wrapped in a namespace so the
        // generated `Py_*` names never collide with user code. Empty if no class
        // has a virtual method.
        inline std::string trampolines_of(const GenContext &c) {
            std::string body;
            for (const auto &k : c.classes) {
                body += trampoline_for(k);
            }
            if (body.empty()) {
                return {};
            }
            // `using namespace std;` is scoped to this trampoline-only namespace so
            // override signatures that reproduce a parameter's exact spelling resolve
            // unqualified std names (display_string_of drops `std::`, e.g.
            // `vector<double, allocator<double>>`). It cannot leak into — or create
            // ambiguities with — the binding-registration code or user headers.
            return "\nnamespace rosetta_py {\nusing namespace std;\n" + body +
                   "} // namespace rosetta_py\n";
        }

        inline bool px_interop_caster(const std::string &name) { return name == "eigen"; }

        // pybind11's caster header for each opted-in foreign library
        // (GenContext::interop).
        inline std::string px_interop_includes(const std::vector<std::string> &names) {
            std::string s;
            for (const auto &n : names) {
                if (n == "eigen") {
                    // Marshals every dense Eigen type to / from numpy, by
                    // reference where the layouts allow it (Eigen::Ref) and by
                    // copy otherwise. Needs Eigen on the include path — which
                    // the manifest's `user_include` already carries into the
                    // generated CMakeLists.
                    s += "#include <pybind11/eigen.h>\n";
                }
            }
            return s;
        }

        // The #include block: pybind11 + the user headers. No rosetta header, so
        // the TU pulls in no reflection machinery whatsoever.
        inline std::string expanded_includes(const GenContext &c) {
            std::string s = "#include <pybind11/pybind11.h>\n"
                            "#include <pybind11/stl.h>\n"
                            "#include <pybind11/stl/filesystem.h>\n"
                            "#include <pybind11/functional.h>\n"
                            "#include <algorithm>\n"
                            "#include <filesystem>\n" // the path adapter
                            "#include <memory>\n"     // std::shared_ptr holders
                            "#include <type_traits>\n"
                            "#include <vector>\n";
            // Caster headers for the opted-in foreign libraries (manifest
            // "interop"). Without one, a signature naming an Eigen type still
            // COMPILES and then throws at call time — the shape the STL-caster
            // fix already ran into. The walk only marks these types when the
            // opt-in is present, so the include and the marking cannot drift.
            s += px_interop_includes(c.interop);
            auto add = [&](const std::string &h) { append_include(s, h); };
            s += init_includes(c);
            for (const auto &k : c.classes) {
                add(k.header);
                for (const auto &m : k.methods) {
                    if (m.is_extension && !m.ext_header.empty()) {
                        add(m.ext_header); // the free function behind an extension method
                    }
                }
            }
            for (const auto &e : c.enums) {
                add(e.header);
            }
            for (const auto &f : c.functions) {
                add(f.header);
            }
            return s;
        }

        // --- Marshalling gates -------------------------------------------------
        // pybind copies at several boundaries: def_readwrite's setter
        // copy-assigns, a by-value class parameter copy-constructs, and the
        // automatic return policy COPIES an lvalue-ref return. Where the copy
        // is deleted the emitted line would not compile, so gate on the
        // copyability captured in the IR. A class whose data API lives in
        // non-copyable public members (GEO::Mesh) then binds as an opaque
        // handle instead of breaking the build.

        // Can this type ride a def_readwrite / vector caster (which copy)?
        inline bool px_copyable(const GenType &t) {
            if (t.kind == "object") {
                return t.copy_constructible && t.copy_assignable;
            }
            if (t.kind == "vector") {
                return t.element.empty() || px_copyable(t.element.front());
            }
            return true;
        }

        // Forward declaration — defined with the member-object helpers below.
        inline bool px_is_bound_class(const GenType &t, const GenContext &c);

        // Can pybind even INSTANTIATE a caster for this type? It compiles one
        // for every complete type, so the hole is a raw pointer: `typeid` of an
        // incomplete pointee is a hard error at the binding's compile time
        // (Model::tabularMedium() returning a forward-declared TabularMedium*).
        // Gate a pointer on its pointee being itself bound — a bound class is
        // complete, and the handle is actually usable from the script side.
        inline bool px_marshalable(const GenType &t, const GenContext &c) {
            if (t.is_pointer) {
                return px_is_bound_class(t, c);
            }
            if (t.is_callback) {
                return true; // pybind11/functional.h marshals std::function
            }
            if (!t.interop.empty()) {
                // A type from an opted-in foreign library (rosetta/interop.h):
                // the caster header emitted by px_interop_includes() owns the
                // conversion, so the type binds exactly as spelled — no adapter
                // and no copy. Nothing else to check here: the caster, not
                // pybind's generic machinery, decides what the boundary costs.
                return px_interop_caster(t.interop);
            }
            if (t.kind == "unknown" && !is_adapted(t)) {
                // A raw C array (Matrix33::data() -> double[3][3]&) or another
                // exotic the IR could not classify: no caster, and its exact
                // spelling cannot even ride the overload-survivor static_cast.
                return false;
            }
            if (t.kind == "vector" && !t.element.empty()) {
                return px_marshalable(t.element.front(), c);
            }
            // A class the module never registered has no caster: pybind11 binds
            // the member and then throws "Unable to convert function return
            // value to a Python type" the first time it is called
            // (GEO::CSGCompiler::builder() returning an unbound
            // GEO::CSGBuilder&). std:: spellings are exempt — <pybind11/stl.h>
            // and its siblings cover map / pair / tuple / optional / variant /
            // array, none of which is a bound class either. A shared_ptr asks
            // about its pointee, which is where the holder lives.
            if (t.kind == "object") {
                const GenType    &q  = shared_pointee(t);
                const std::string sp = q.object_qualified.empty() ? q.spelling : q.object_qualified;
                return px_is_bound_class(q, c) || sp.rfind("std::", 0) == 0;
            }
            return true;
        }

        inline bool px_field_ok(const GenField &f, const GenContext &c) {
            return px_marshalable(f.type, c) && px_copyable(f.type);
        }

        // Defined below (it needs the bound-class lookup): does this method
        // return an lvalue reference that binds with `reference_internal`?
        inline bool px_ref_return(const GenMethod &m, const GenContext &c);

        // Defined below (they need the bound-class lookup): is this type a raw
        // pointer to a bound class, and what keep_alive attributes does a
        // method's parameter list need? Declared here because the sequence
        // adapter above emits methods too.
        inline bool        px_borrowed_pointer(const GenType &t, const GenContext &c);
        inline std::string px_keep_alive(const GenMethod &m, const GenContext &c,
                                         const char *ns);

        inline bool px_method_ok(const GenMethod &m, const GenContext &c) {
            // An overload set is NOT rejected here: the walk keeps its
            // first-declared entry, and expanded_method() spells an explicit
            // static_cast to that entry's exact signature, so the member
            // pointer is unambiguous. The remaining gates below check the
            // survivor's own signature as usual.
            // An overload needs its exact signature spelled for the cast; a
            // type with no name of its own cannot be. See sig_spellable().
            if (m.is_overloaded && !sig_spellable(m)) {
                return false;
            }
            if (!px_marshalable(m.ret, c)) {
                return false;
            }
            // A by-value class return needs copy/move (copy_constructible is
            // the conservative proxy for both), and so did an lvalue-ref return
            // back when the automatic policy copied it. It no longer does:
            // px_ref_return attaches `reference_internal`, which hands Python
            // the object itself. So a non-copyable class is a perfectly good
            // REFERENCE return — `facet_corners.attributes()` handing out the
            // mesh's own AttributesManager — and only the by-value case is
            // still out.
            if (m.ret.kind == "object" && !m.ret.copy_constructible &&
                !px_ref_return(m, c)) {
                return false;
            }
            if (m.ret.kind == "vector" && !px_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (!px_marshalable(p.type, c)) {
                    return false;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false; // by-value class parameter copy-constructs
                }
                if (p.type.kind == "vector" && !px_copyable(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // Why px_method_ok said no, as one human sentence for the coverage
        // report. Deliberately mirrors that function's gates in the same order:
        // a reason that drifts out of step with the decision is worse than no
        // reason, so the two are meant to be read (and edited) side by side.
        inline std::string px_skip_reason(const GenMethod &m, const GenContext &c) {
            if (!px_marshalable(m.ret, c)) {
                return "no pybind11 type-caster for the return type '" +
                       (m.ret_cpp.empty() ? m.ret.spelling : m.ret_cpp) + "'";
            }
            if (m.ret.kind == "object" && !m.ret.copy_constructible && !px_ref_return(m, c)) {
                return "returns '" + m.ret.spelling +
                       "' by value or by reference, and it is not copy-constructible (pybind's "
                       "automatic return policy copies)";
            }
            if (m.ret.kind == "vector" && !px_copyable(m.ret)) {
                return "returns a vector whose element type is not copyable";
            }
            for (std::size_t i = 0; i < m.params.size(); ++i) {
                const GenParam   &p  = m.params[i];
                const std::string at = " (parameter " + std::to_string(i + 1) + ")";
                if (!px_marshalable(p.type, c)) {
                    return "no pybind11 type-caster for '" + p.type.spelling + "'" + at;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return "takes '" + p.type.spelling +
                           "' by value and it is not copy-constructible" + at;
                }
                if (p.type.kind == "vector" && !px_copyable(p.type)) {
                    return "takes a vector whose element type is not copyable" + at;
                }
            }
            return "rejected by the python marshalling gates";
        }

        // Explicit pybind for one enum: py::enum_<E>(m,"E").value("A", E::A)...;
        inline std::string expanded_enum(const GenEnum &e) {
            const std::string eq = qualified_of(e);
            std::string       s  = "    py::enum_<" + eq + ">(m, \"" + exposed_of(e) + "\")";
            for (const auto &v : e.values) {
                s += "\n        .value(\"" + v.name + "\", " + eq + "::" + v.name + ")";
            }
            s += ";\n";
            return s;
        }

        // Explicit pybind for one field, mirroring PybindVisitor::field():
        // readonly -> def_readonly; arithmetic + range -> validating def_property;
        // otherwise def_readwrite. Member pointers keep the field type implicit,
        // so no type spelling is needed except for the range setter's parameter.
        inline std::string expanded_field(const GenClass &k, const GenField &f) {
            const std::string self  = qualified_of(k);
            const std::string mp    = "&" + self + "::" + f.name; // member pointer
            const std::string dq    = doc_arg(f.doc);
            if (f.is_readonly) {
                return "    c.def_readonly(\"" + f.name + "\", " + mp + dq + ");\n";
            }
            if (f.range.has && f.type.kind == "number") {
                const std::string ty  = f.type.spelling; // arithmetic -> compilable spelling
                const std::string lo  = num_str(f.range.min);
                const std::string hi  = num_str(f.range.max);
                std::string s;
                s += "    c.def_property(\"" + f.name + "\",\n";
                s += "        [](const " + self + " &s) { return s." + f.name + "; },\n";
                s += "        [](" + self + " &s, " + ty + " v) {\n";
                s += "            if (v < " + lo + " || v > " + hi + ")\n";
                s += "                throw py::value_error(\"" + f.name + " out of range [" + lo +
                     ", " + hi + "]\");\n";
                s += "            s." + f.name + " = v;\n";
                s += "        }" + dq + ");\n";
                return s;
            }
            return "    c.def_readwrite(\"" + f.name + "\", " + mp + dq + ");\n";
        }

        // Member-object property: a public data member whose type is another
        // BOUND class but is not copyable (a plain def_readwrite/def_readonly
        // would copy). Emitted as a read-only property returning a reference,
        // with reference_internal so the parent outlives every child handle —
        // `mesh.vertices` hands out the real MeshVertices living inside the
        // mesh. This is what makes struct-of-member-objects APIs (GEO::Mesh)
        // reachable without a flat-array facade.
        // Resolve a field/param class type against the bound-class list. The
        // qualified spelling is compared when the IR carries it (two bound
        // classes may share an unqualified identifier — the "expose" rename
        // case); the unqualified fallback keeps hand-built IR working.
        inline bool px_is_bound_class(const GenType &t, const GenContext &c) {
            for (const auto &k : c.classes) {
                if (t.object_qualified.empty() ? (k.name == t.object)
                                               : (qualified_of(k) == t.object_qualified)) {
                    return true;
                }
            }
            return false;
        }

        inline std::string expanded_member_object(const GenClass &k, const GenField &f) {
            const std::string dq = doc_arg(f.doc);
            const std::string ft =
                f.type.object_qualified.empty() ? f.type.object : f.type.object_qualified;
            std::string s;
            s += "    c.def_property_readonly(\"" + f.name + "\",\n";
            s += "        [](" + qualified_of(k) + " &s) -> " + ft + " & { return s." +
                 f.name + "; },\n";
            s += "        py::return_value_policy::reference_internal" + dq + ");\n";
            return s;
        }

        // --- Foreign containers (rosetta::is_sequence / is_matrix) -------------
        // A method touching a trait-registered sequence binds through a lambda
        // adapter: the script side speaks std::vector<element> (pybind's stl.h
        // caster), the adapter builds the foreign container before the call and
        // flattens a returned one after. The adapter calls the method BY NAME
        // with concrete arguments, so — unlike the member-pointer path — an
        // overload set whose surviving IR entry is the sequence overload binds
        // (GEO::MeshVertices::assign_points). A mutable `Seq&` parameter binds
        // input-only: the adapter's local container is a real lvalue and
        // in-place mutations are discarded, exactly like pybind's std::vector&.

        // A compilable value/reference spelling for adapter parameters that
        // carry no exact param_cpp (extension methods, free functions).
        inline std::string px_cpp_type(const GenType &t) {
            if (!t.interop.empty()) {
                // Foreign-library type: `spelling` is the full template spelling
                // but display_string_of prints the template name unqualified
                // ("Matrix<double, -1, 1, …>"), and the emitted `using namespace`
                // block only opens the BOUND namespaces. qualify_objects swaps
                // the bare token for object_qualified ("Eigen::Matrix"), which
                // resolves wherever the adapter lands.
                return qualify_objects(t.spelling, t);
            }
            if (t.kind == "vector") {
                return "std::vector<" +
                       (t.element.empty() ? std::string("double")
                                          : px_cpp_type(t.element.front())) +
                       ">";
            }
            if (t.kind == "object" || t.kind == "enum") {
                // Qualified when known: the unqualified identifier is ambiguous
                // once two bound namespaces declare it (the "expose" case).
                return t.object_qualified.empty() ? t.object : t.object_qualified;
            }
            if (t.kind == "string") {
                return "std::string";
            }
            if (t.kind == "boolean") {
                return "bool";
            }
            if (t.kind == "number") {
                return t.spelling.empty() ? "double" : t.spelling;
            }
            return qualify_std(t.spelling);
        }

        // Do the NON-sequence parts of the signature still satisfy the python
        // gates? (The sequence parts go through the adapter, which lifts the
        // vector-copy and overload restrictions.)
        // Does this signature need the copy ADAPTER here? The same question
        // seq_touches asks, minus std::filesystem::path: pybind11 and nanobind
        // ship their own path caster (<pybind11/stl/filesystem.h> /
        // <nanobind/stl/filesystem.h>, both in the emitted include block), so a
        // path binds NATIVELY in this family — and Python may then pass a str or
        // any os.PathLike, where the std::string boundary the caster-less
        // backends need would refuse a pathlib.Path. A signature that also
        // touches a foreign container still takes the adapter, which converts
        // the path too (correct either way, and one code path instead of two).
        inline bool px_touches(const GenMethod &m) {
            auto adapts = [](const GenType &t) { return is_adapted(t) && !t.is_path; };
            if (adapts(m.ret)) {
                return true;
            }
            for (const auto &p : m.params) {
                // An out-parameter needs the adapter here as much as anywhere:
                // the caller does not pass it, and its value joins the return.
                if (adapts(p.type) || is_out_param(p)) {
                    return true;
                }
            }
            return false;
        }

        inline bool px_seq_rest_ok(const GenMethod &m, const GenContext &c) {
            if (!is_adapted(m.ret) && !px_marshalable(m.ret, c)) {
                return false;
            }
            if (m.ret.kind == "object" && !m.ret.copy_constructible) {
                return false;
            }
            if (m.ret.kind == "vector" && !px_copyable(m.ret)) {
                return false;
            }
            for (const auto &p : m.params) {
                if (is_adapted(p.type) || is_out_param(p)) {
                    continue;
                }
                if (!px_marshalable(p.type, c)) {
                    return false;
                }
                if (p.type.kind == "object" && !p.is_ref && !p.type.copy_constructible) {
                    return false;
                }
                if (p.type.kind == "vector" && !px_copyable(p.type)) {
                    return false;
                }
            }
            return true;
        }

        // The adapter lambda's (parameter decls, pre-call statements, call args).
        struct PxSeqSig {
            std::string decls;
            std::string pre;
            std::string args;
            // Out-parameters: locals the adapter declared and passes by
            // reference, whose values join the return (see out_return_stmts).
            std::vector<OutParam> outs;
        };
        inline PxSeqSig px_seq_sig(const std::vector<GenParam>    &params,
                                   const std::vector<std::string> &param_cpp) {
            PxSeqSig    o;
            const bool  exact = param_cpp.size() == params.size();
            // Declarations and arguments are collected separately and joined at
            // the end: an out-parameter contributes an ARGUMENT (the local) but
            // no DECLARATION, so the two lists no longer run in lockstep.
            std::vector<std::string> decls, args;
            for (std::size_t j = 0; j < params.size(); ++j) {
                const std::string an = "arg" + std::to_string(j);
                const GenType    &t  = params[j].type;
                if (is_out_param(params[j])) {
                    // The caller does not pass an out-parameter, it receives
                    // one: a local goes in, its value comes back with the
                    // return (see out_return_stmts).
                    const std::string on = "out" + std::to_string(j);
                    o.pre += "        " + out_local_cpp(t) + " " + on + "{};\n";
                    args.push_back(on);
                    o.outs.push_back({on, out_expr(t, on)});
                    continue;
                }
                if (is_adapted(t)) {
                    const std::string sn = adapt_local(t, j);
                    decls.push_back(adapt_boundary_cpp(t) + " " + an);
                    o.pre += adapt_decl_stmts(t, an, sn, "        ");
                    args.push_back(sn);
                } else if (exact) {
                    decls.push_back(qualify_objects(qualify_std(param_cpp[j]), t) + " " + an);
                    args.push_back(an);
                } else if (t.kind == "object") {
                    decls.push_back(px_cpp_type(t) + " &" + an); // bound class, by ref
                    args.push_back(an);
                } else {
                    decls.push_back(px_cpp_type(t) + " " + an);
                    args.push_back(an);
                }
            }
            o.decls = join(decls, ", ");
            o.args  = join(args, ", ");
            return o;
        }

        // The full def(...) for a sequence-adapted method / extension / static.
        inline std::string px_seq_method(const GenClass &k, const GenMethod &m,
                                         const GenContext &c) {
            const PxSeqSig    sig = px_seq_sig(m.params, m.param_cpp);
            const std::string kq  = qualified_of(k);
            std::string       decls, call;
            if (m.is_extension) {
                decls = kq + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = m.ext_qualified + "(self" + (sig.args.empty() ? "" : ", " + sig.args) +
                       ")";
            } else if (m.is_static) {
                decls = sig.decls;
                call  = kq + "::" + m.name + "(" + sig.args + ")";
            } else {
                decls = kq + " &self" + (sig.decls.empty() ? "" : ", " + sig.decls);
                call  = "self." + m.name + "(" + sig.args + ")";
            }
            std::string body = sig.pre;
            if (!sig.outs.empty()) {
                // pybind11 marshals a std::tuple as a Python tuple, so an
                // out-parameter comes back as an extra element.
                body += out_return_stmts(m, sig.outs, call, "        ");
            } else if (is_adapted(m.ret)) {
                body += "        auto &&r = " + call + ";\n";
                body += "        return " + adapt_from_expr(m.ret, "r") + ";\n";
            } else if (m.ret.kind == "void") {
                body += "        " + call + ";\n";
            } else {
                body += "        return " + call + ";\n";
            }
            const std::string def = m.is_static ? "def_static" : "def";
            return "    c." + def + "(\"" + m.name + "\", [](" + decls + ") {\n" + body +
                   "    }" + px_keep_alive(m, c, "py") + doc_arg(px_method_doc(m)) +
                   px_arg_list(m.params, "py", c) + ");\n";
        }

        // A sequence-typed field: def_property copying through the boundary
        // vector in both directions (member pointers would hand pybind the
        // casterless foreign type).
        inline std::string px_seq_field(const GenClass &k, const GenField &f) {
            const std::string vt = adapt_boundary_cpp(f.type);
            const std::string dq = doc_arg(f.doc);
            std::string       s;
            const std::string get = "[](const " + k.name + " &s) { return " +
                                    adapt_from_expr(f.type, "s." + f.name) + "; }";
            if (f.is_readonly) {
                return "    c.def_property_readonly(\"" + f.name + "\", " + get + dq + ");\n";
            }
            s += "    c.def_property(\"" + f.name + "\",\n";
            s += "        " + get + ",\n";
            s += "        [](" + k.name + " &s, const " + vt + " &v) {\n";
            s += "            s." + f.name + ".resize(v.size());\n";
            s += "            std::copy(v.begin(), v.end(), s." + f.name + ".begin());\n";
            s += "        }" + dq + ");\n";
            return s;
        }

        // Explicit pybind for one method. EVERY overload of a name binds: pybind11
        // collects repeated .def("name", …) into one overload set and dispatches
        // on the argument types at call time, so `at(i)` and `at(i, j)` both reach
        // Python under the same name. Each is spelled through px_member_pointer,
        // which casts away the &T::m ambiguity. An extension method binds its free
        // function instead — pybind treats a free function whose first parameter
        // is T& as an instance method.
        //
        // A raw-pointer return (Model::addSurface() -> Surface*) rides
        // reference_internal (plain reference for a static): pybind's automatic
        // policy would TAKE OWNERSHIP of the pointer, double-freeing an object
        // the C++ side still owns.
        // Should this method's return bind BY REFERENCE rather than by copy?
        // pybind's automatic policy copies an lvalue-reference return, silently
        // and at a cost that grows with the object — a fluent API returning
        // `*this` (`Interpolator &addValueConstraint(...)`) copies the whole
        // receiver on every call, which makes a constraint loop quadratic, and
        // mutations through the handle are lost because they land on the copy.
        // reference_internal is the policy for that shape: no copy, and the
        // returned handle keeps the parent alive for as long as it lives.
        //
        // A CONST reference keeps copying. Python has no notion of constness, so
        // binding one by reference would hand scripts a freely mutable view of
        // something the C++ API deliberately handed out read-only — the copy is
        // the honest reading there. Shared pointers are excluded too: the holder
        // already owns that lifetime question.
        inline bool px_ref_return(const GenMethod &m, const GenContext &c) {
            return m.ret_is_ref && m.ret.kind == "object" && !m.ret.is_shared_ptr &&
                   m.ret_cpp.rfind("const", 0) != 0 && px_is_bound_class(m.ret, c);
        }

        // Is this a RAW POINTER to a bound class — directly (`Surface *`) or as
        // the element of a container (`std::vector<Triangle *>`)? True of a
        // BORROWED handle: an object one side hands the other while the owner
        // keeps using it. Both directions of the boundary need to know.
        //
        // OUT (a return): the automatic policy for a pointer is TAKE_OWNERSHIP,
        // so the binding deletes the pointee when the wrapper is collected.
        // arch::Model::addSurface() returns a Surface the Model keeps in its own
        // list, and Model::triangles() a whole vector of Triangles it owns;
        // letting either wrapper go out of scope frees them under the Model,
        // after which nbDof() silently reports only the surfaces that happen to
        // still be alive and the next solve reads freed memory. Hence
        // reference_internal — see the policy sites.
        //
        // IN (a parameter): the callee may STORE the pointer
        // (Model::addRemote(BaseRemote*) keeps it in a list and Model's
        // destructor deletes nothing), so the argument has to outlive the call.
        // Hence keep_alive — see px_keep_alive.
        //
        // A container is checked through its element because the list casters
        // pass the policy down to each element, so setting it on the vector is
        // what reaches the pointers inside.
        //
        // The cost of both choices is the same, and it is the survivable one:
        // over-retention. A genuine factory (`Triangle *clone() const`) leaks,
        // and pinning the argument of a pure query keeps it alive longer than
        // needed. Nothing in a signature separates those from the borrowing
        // case, so one reading has to be the default, and a leak beats a
        // use-after-free.
        inline bool px_borrowed_pointer(const GenType &t, const GenContext &c) {
            if (t.is_pointer) {
                return px_is_bound_class(t, c);
            }
            if (t.kind == "vector" && !t.element.empty()) {
                return px_borrowed_pointer(t.element.front(), c);
            }
            return false;
        }

        // keep_alive attributes for the pointer parameters of `m`: one
        // `keep_alive<1, N>` per borrowed-pointer argument, tying its lifetime
        // to the receiver's. pybind11 and nanobind spell this identically, so
        // `ns` picks the namespace ("py" / "nb").
        //
        // Slot numbering is the binding's, not C++'s: 1 is `self` and the
        // parameters follow from 2. Out-parameters are skipped because they are
        // not part of the emitted signature (they join the return) — the same
        // filter px_arg_list applies, so the two agree on what argument N is.
        // Extension methods need no adjustment: generate() already strips their
        // leading `T&`, so their m.params start at slot 2 like a member's.
        //
        // Static methods and free functions get nothing: with no receiver there
        // is no nurse to tie the argument to. A static factory that stores its
        // argument would need `keep_alive<0, N>` (return value as nurse), which
        // is a different claim about ownership than this one and should be
        // stated explicitly rather than guessed.
        inline std::string px_keep_alive(const GenMethod &m, const GenContext &c,
                                         const char *ns) {
            if (m.is_static) {
                return {};
            }
            std::string out;
            std::size_t slot = 2; // 1 is self
            for (const auto &p : m.params) {
                if (is_out_param(p)) {
                    continue;
                }
                if (px_borrowed_pointer(p.type, c)) {
                    out += ", " + std::string(ns) + "::keep_alive<1, " + std::to_string(slot) +
                           ">()";
                }
                ++slot;
            }
            return out;
        }

        // The member-function-pointer expression for `m`, disambiguated when it
        // needs to be. `&T::name` names an OVERLOAD SET, not a function, so for
        // any name the C++ class declares more than once it must be resolved by
        // an explicit cast to this entry's exact signature — otherwise the
        // emitted line does not compile. Every expanded backend that spells a
        // member pointer needs exactly this, so it lives here (python is
        // included before the others — see the include block in generate.hxx) and
        // is shared rather than re-derived per backend.
        //
        // Note the gate is `is_overloaded` (does the C++ class overload the
        // name?) and NOT `overload_count` (how many entries reached the IR): a
        // set whose siblings were all gated out still needs the cast.
        inline std::string px_member_pointer(const GenClass &k, const GenMethod &m) {
            const std::string kq = qualified_of(k);
            const std::string mp = "&" + kq + "::" + m.name;
            if (!m.is_overloaded) {
                return mp;
            }
            std::string args;
            for (std::size_t j = 0; j < m.param_cpp.size(); ++j) {
                std::string one = qualify_std(m.param_cpp[j]);
                if (j < m.params.size()) {
                    one = qualify_objects(std::move(one), m.params[j].type);
                }
                args += (j ? ", " : "") + one;
            }
            std::string quals;
            if (m.is_const) {
                quals += " const";
            }
            if (m.is_noexcept) {
                quals += " noexcept";
            }
            const std::string ret = qualify_objects(qualify_std(m.ret_cpp), m.ret);
            const std::string fp  = m.is_static
                                        ? (ret + " (*)(" + args + ")" + quals)
                                        : (ret + " (" + kq + "::*)(" + args + ")" + quals);
            return "static_cast<" + fp + ">(" + mp + ")";
        }

        inline std::string expanded_method(const GenClass &k, const GenMethod &m,
                                           const GenContext &c) {
            const std::string dq = doc_arg(px_method_doc(m));
            const std::string aq = px_arg_list(m.params, "py", c);
            const std::string ka = px_keep_alive(m, c, "py");
            // A fluent extension (`Cls &fn(Cls &, …)`) needs the policy for the
            // same reason a member does — it binds as an instance method, so
            // `self` is argument 1 either way.
            const std::string policy =
                (px_borrowed_pointer(m.ret, c) || px_ref_return(m, c))
                    ? (m.is_static ? ", py::return_value_policy::reference"
                                   : ", py::return_value_policy::reference_internal")
                    : "";
            if (m.is_extension) {
                return "    c.def(\"" + m.name + "\", &" + m.ext_qualified + policy + ka + dq +
                       aq + ");\n";
            }
            const std::string mp = px_member_pointer(k, m);
            if (m.is_static) {
                return "    c.def_static(\"" + m.name + "\", " + mp + policy + ka + dq + aq +
                       ");\n";
            }
            return "    c.def(\"" + m.name + "\", " + mp + policy + ka + dq + aq + ");\n";
        }

        // The constructors, as py::init<...>() lines. Exact param spellings come
        // from GenClass::ctor_param_cpp; a synthetic py::init<>() is added when T
        // is default-constructible but no zero-arg ctor was enumerated. A ctor
        // whose signature pybind cannot even instantiate a caster for (raw
        // pointer to an unbound class — `typeid` of an incomplete type) is
        // skipped, mirroring the method gates.
        //
        // For an abstract class the init lines allocate the trampoline, and a
        // pure virtual the trampoline could NOT override (protected, or an
        // unbindable signature) leaves Py_X itself abstract — undetectable from
        // the IR. So the block is emitted inside a generic lambda behind
        // `if constexpr (!std::is_abstract_v<Py_X>)`: when the trampoline is
        // complete the constructors bind (Python subclassing keeps working),
        // otherwise the block compiles away instead of breaking the build.
        inline std::string expanded_ctors(const GenClass &k, const GenContext &c,
                                          bool has_tramp) {
            std::string s;
            bool        saw_default = false;
            for (std::size_t i = 0; i < k.ctor_param_cpp.size(); ++i) {
                bool ok = true;
                if (i < k.ctors.size()) {
                    for (const auto &p : k.ctors[i]) {
                        ok = ok && px_marshalable(p.type, c) &&
                             !(p.type.kind == "object" && !p.is_ref &&
                               !p.type.copy_constructible) &&
                             !(p.type.kind == "vector" && !px_copyable(p.type));
                    }
                }
                if (!ok) {
                    continue;
                }
                const auto &params = k.ctor_param_cpp[i];
                if (params.empty()) {
                    saw_default = true;
                }
                std::string args;
                for (std::size_t j = 0; j < params.size(); ++j) {
                    std::string one = qualify_std(params[j]);
                    if (i < k.ctors.size() && j < k.ctors[i].size()) {
                        one = qualify_objects(std::move(one), k.ctors[i][j].type);
                    }
                    args += (j ? ", " : "") + one;
                }
                s += "    c.def(py::init<" + args + ">());\n";
            }
            if (!saw_default && k.is_default_constructible) {
                s += "    c.def(py::init<>());\n";
            }
            if (s.empty() || !k.is_abstract) {
                return s;
            }
            if (!has_tramp) {
                return {}; // abstract, no trampoline — never instantiable
            }
            std::string guarded =
                "    [](auto &c) {\n"
                "        if constexpr (!std::is_abstract_v<rosetta_py::Py_" +
                exposed_of(k) + ">) {\n";
            std::size_t i = 0;
            while (i < s.size()) {
                std::size_t nl = s.find('\n', i);
                if (nl == std::string::npos) {
                    nl = s.size();
                }
                guarded += "        " + s.substr(i, nl - i + 1);
                i = nl + 1;
            }
            guarded += "        }\n    }(c);\n";
            return guarded;
        }

        // One class block: an open scope so the local `c` never leaks. Uses the
        // trampoline (py::class_<T, Py_T>) when the class has virtual methods —
        // the trampoline classes themselves are emitted, verbatim, by the
        // existing reflection-free trampolines_of() helper. Bound base classes
        // ride as extra template args so pybind accepts a derived instance
        // where a base is expected (a base must be registered before its
        // derived — that follows from manifest order).
        // Walk one type (and its element / callback children) for shared_ptr
        // pointees that name a class, collecting their qualified spellings.
        inline std::vector<std::string> px_shared_holders(const GenContext &c) {
            std::vector<std::string> need = shared_pointees(c);
            // pybind requires one holder per inheritance chain: registering a
            // base with std::shared_ptr and a derived with the default holder
            // (or the reverse) is a runtime error the moment either crosses the
            // boundary. Propagate both ways until the set stops growing —
            // `local()` returning shared_ptr<Executor> is what drags
            // LocalExecutor and RemoteExecutor in.
            auto has = [&](const std::string &q) {
                return std::find(need.begin(), need.end(), q) != need.end();
            };
            for (bool changed = true; changed;) {
                changed = false;
                for (const auto &k : c.classes) {
                    const std::string kq = qualified_of(k);
                    for (const auto &b : k.bases) {
                        bool bound = false;
                        for (const auto &g : c.classes) {
                            bound = bound || qualified_of(g) == b;
                        }
                        if (!bound) {
                            continue;
                        }
                        if (has(b) && !has(kq)) {
                            need.push_back(kq);
                            changed = true;
                        } else if (has(kq) && !has(b)) {
                            need.push_back(b);
                            changed = true;
                        }
                    }
                }
            }
            return need;
        }

        inline std::string expanded_class(const GenClass &k, const GenContext &c) {
            // A class whose destructor is not public cannot be wrapped: every
            // runtime backend destroys what it holds. Skip it with a note —
            // the alternative is a compile error inside the framework headers.
            if (!k.is_destructible) {
                std::fprintf(stderr,
                             "rosetta::%s: class '%s' has a non-public destructor "
                             "(ref-counted?) — skipped\n",
                             "python", k.name.c_str());
                return {};
            }

            const bool        has_tramp = !virtual_methods(k).empty();
            const std::string kq        = qualified_of(k);
            std::string       extra;
            // Holder first — py::class_ detects its options by type, so the
            // order among trampoline / holder / bases is free.
            const auto shared = px_shared_holders(c);
            if (std::find(shared.begin(), shared.end(), kq) != shared.end()) {
                extra += ", std::shared_ptr<" + kq + ">";
            }
            if (has_tramp) {
                extra += ", rosetta_py::Py_" + exposed_of(k);
            }
            for (const auto &b : k.bases) {
                for (const auto &g : c.classes) {
                    if (qualified_of(g) == b) {
                        extra += ", " + b;
                        break;
                    }
                }
            }
            const std::string decl = "py::class_<" + kq + extra + ">";
            // The class's own doc comment becomes the Python type's docstring —
            // what `help(Cls)` prints above the members.
            std::string s = "    {\n        " + decl + " c(m, \"" + exposed_of(k) + "\"" +
                            doc_arg(k.brief) + ");\n";
            // The block-local helper lines are written at one indent; reuse the
            // module-level emitters and shift them in by four spaces.
            auto indent = [](const std::string &block) {
                std::string out;
                std::size_t i = 0;
                while (i < block.size()) {
                    std::size_t nl = block.find('\n', i);
                    if (nl == std::string::npos) {
                        nl = block.size();
                    }
                    out += "    " + block.substr(i, nl - i + 1);
                    i = nl + 1;
                }
                return out;
            };
            s += indent(expanded_ctors(k, c, has_tramp));
            for (const auto &f : k.fields) {
                if (is_adapted(f.type)) {
                    if (adapt_ok(f.type)) {
                        s += indent(px_seq_field(k, f));
                    }
                    continue; // never hand pybind the casterless foreign type
                }
                if (!px_field_ok(f, c)) {
                    // A non-copyable member object of a BOUND class becomes a
                    // reference property (methods win on a name clash — e.g. a
                    // manifest extension already named like the field).
                    bool clashes = false;
                    for (const auto &m : k.methods) {
                        clashes = clashes || m.name == f.name;
                    }
                    if (f.type.kind == "object" && px_is_bound_class(f.type, c) &&
                        !clashes) {
                        s += indent(expanded_member_object(k, f));
                    }
                    continue; // anything else non-copyable — see px_copyable
                }
                s += indent(expanded_field(k, f));
            }
            for (const auto &m : k.methods) {
                if (px_touches(m)) {
                    // Foreign sequence in the signature: adapter or nothing —
                    // the member-pointer path would hand pybind the casterless
                    // foreign type (and an overloaded set is fine here, see
                    // px_seq_method).
                    if (seq_adaptable(m) && px_seq_rest_ok(m, c)) {
                        s += indent(px_seq_method(k, m, c));
                        coverage::note_bound("python", k, m);
                    } else {
                        coverage::note_skip("python", k, m, "sequence_not_adaptable",
                                            "a registered sequence in the signature has no "
                                            "std::vector boundary adapter for this backend");
                    }
                    continue;
                }
                if (!px_method_ok(m, c)) {
                    coverage::note_skip("python", k, m, "unmarshalable_signature",
                                        px_skip_reason(m, c));
                    continue; // signature the emitted pybind line could not compile
                }
                s += indent(expanded_method(k, m, c));
                coverage::note_bound("python", k, m);
            }
            s += "    }\n";
            return s;
        }

        inline std::string python_expanded_source(const GenContext &c0) {
            // A type marked BOTH ways — a registered sequence that an opted-in
            // interop library owns (Eigen::VectorXd under "sequences" +
            // "interop": ["eigen"]) — binds through the CASTER here: numpy, both
            // directions, against a copied Python list from the adapter. Dropping
            // the sequence marks once, on this local copy, is what says that; the
            // gates below then read it as the plain interop type it is.
            const GenContext c = interop_wins(c0, px_interop_caster);
            std::string      body;
            for (const auto &e : c.enums) {
                body += expanded_enum(e);
            }
            for (const auto &k : c.classes) {
                body += expanded_class(k, c);
            }
            for (const auto &f : c.functions) {
                GenMethod probe; // free functions go through the same gates
                probe.ret    = f.ret;
                probe.params = f.params;
                if (px_touches(probe)) {
                    if (seq_adaptable(probe) && px_seq_rest_ok(probe, c)) {
                        const PxSeqSig sig = px_seq_sig(f.params, {});
                        std::string body2 = sig.pre;
                        const std::string call = fn_call_expr(f) + "(" + sig.args + ")";
                        if (!sig.outs.empty()) {
                            body2 += out_return_stmts(probe, sig.outs, call, "        ");
                        } else if (is_adapted(f.ret)) {
                            body2 += "        auto &&r = " + call + ";\n";
                            body2 += "        return " + adapt_from_expr(f.ret, "r") + ";\n";
                        } else if (f.ret.kind == "void") {
                            body2 += "        " + call + ";\n";
                        } else {
                            body2 += "        return " + call + ";\n";
                        }
                        body += "    m.def(\"" + f.name + "\", [](" + sig.decls + ") {\n" +
                                body2 + "    }" + doc_arg(px_method_doc(f)) +
                                px_arg_list(f.params, "py", c) + ");\n";
                        coverage::note_bound_function("python", f);
                    } else {
                        coverage::note_skip_function("python", f, "sequence_not_adaptable",
                                                     "a registered sequence in the signature has "
                                                     "no std::vector boundary adapter");
                    }
                    continue;
                }
                if (!px_method_ok(probe, c)) {
                    coverage::note_skip_function("python", f, "unmarshalable_signature",
                                                 "no pybind11 type-caster for a type in this "
                                                 "signature");
                    continue;
                }
                body += "    m.def(\"" + f.name + "\", " + fn_addr(f) + doc_arg(px_method_doc(f)) +
                        px_arg_list(f.params, "py", c) + ");\n";
                coverage::note_bound_function("python", f);
            }

            std::string out = "// Generated by rosetta::generate (expanded, reflection-free) — "
                              "do not edit by hand.\n";
            out += expanded_includes(c);
            out += using_namespaces_of(c); // `using namespace` for namespaced user types
            out += "\nnamespace py = pybind11;\n";
            out += trampolines_of(c); // reflection-free; empty when no virtuals
            out += "\nPYBIND11_MODULE(" + c.lib + ", m) {\n";
            out += init_block(c);
            out += "    m.doc() = \"Auto-generated (expanded) bindings for " + c.lib + ".\";\n";
            out += body;
            out += "}\n";
            return out;
        }

        inline std::string Python::render(const GenContext &c) const {
            return python_expanded_source(c);
        }

        inline void Python::emit(const GenContext &c) const {
            auto dir = c.out_dir / "python";
            write_file(dir / "auto_pybind.cpp", python_expanded_source(c));
            write_file(dir / "CMakeLists.txt", render_meta(PYX_CMAKE, c));
            // Wheel packaging: pyproject.toml (scikit-build-core, driving the
            // CMakeLists above) plus the builder script. render_meta supplies
            // {{VERSION}} from the manifest's "version".
            write_file(dir / "pyproject.toml", render_meta(PYX_PYPROJECT, c));
            write_script(dir / "make_wheel.py",
                         subst(PYX_MAKE_WHEEL,
                               {{"LIB", c.lib}, {"USER_LIB_DIRS", py_dir_list(c)}}));
            write_file(dir / "README.md",
                       readme("python", c,
                              subst(PYX_README_BUILD, {{"LIB", c.lib}}) + "\n\n" +
                                  subst(PYX_README_WHEEL, {{"ABI_NOTE", PYX_ABI_NOTE}})));
        }

    } // namespace backend
} // namespace rosetta
