// Copyright (c) fmaerten@gmail.com
// License: MIT

// The generator-project emitters: bindings.h (binding_info specializations +
// baked-in annotations), <generator_name>.cpp (the reflection driver's main)
// and its CMakeLists.txt.

#include "emit.h"
#include "util.h"

#include <algorithm>
#include <cstdio>
#include <sstream>
#include <string>
#include <vector>

// Defaults baked into the driver CMakeLists when the manifest omits a field.
// Kept in sync with rosetta::gen_detail::DEFAULT_CPP26_*. The compiler / stdlib
// defaults are CMake expressions deriving from CLANG_P2996_ROOT, so setting only
// "cpp26_root" moves all three together.
static const char *kDefaultCpp26Root = "$ENV{HOME}/devs/c++/clang-p2996/build";
static const char *kDefaultCpp26Cxx  = "${CLANG_P2996_ROOT}/bin/clang++";
static const char *kDefaultCpp26Cc   = "${CLANG_P2996_ROOT}/bin/clang";
static const char *kDefaultCpp26Lib  = "${CLANG_P2996_ROOT}/lib";

// Any string -> a C++ string literal that reproduces it exactly.
//
// Escaped rather than raw: a harvested docstring is arbitrary user prose, and a
// raw literal needs a delimiter guaranteed absent from the text — a guarantee
// no fixed delimiter has. Escaping has no such failure mode. Bytes >= 0x80 pass
// through untouched so UTF-8 survives; the control characters that would end or
// confuse the literal are the only ones spelled numerically.
static std::string str_lit(const std::string &s) {
    std::string out = "\"";
    for (unsigned char ch : s) {
        switch (ch) {
        case '"':  out += "\\\""; break;
        case '\\': out += "\\\\"; break;
        case '\n': out += "\\n";  break;
        case '\r': out += "\\r";  break;
        case '\t': out += "\\t";  break;
        default:
            if (ch < 0x20 || ch == 0x7f) {
                char buf[8];
                // Hex escapes are greedy in C++, so close the literal and
                // reopen it: "\x0c" followed by 'a' would otherwise read as
                // one huge hex escape.
                std::snprintf(buf, sizeof buf, "\\x%02x", ch);
                out += buf;
                out += "\"\"";
            } else {
                out += static_cast<char>(ch);
            }
            break;
        }
    }
    return out + "\"";
}

// JSON bytes -> "char(0x7b), char(0x0a), ..." for a std::to_array<char> literal.
// The explicit char() cast avoids a narrowing error for bytes >= 0x80 (UTF-8).
static std::string render_byte_array(const std::string &data) {
    std::ostringstream out;
    for (unsigned char ch : data) {
        char buf[16];
        std::snprintf(buf, sizeof buf, "char(0x%02x), ", ch);
        out << buf;
    }
    return out.str();
}

static std::string render_bindings_h(const Manifest &m) {
    std::ostringstream out;
    out << "// Generated by rosetta_gen — do not edit by hand.\n"
        << "#pragma once\n\n"
        << "#include <rosetta/generate.h>\n"
        << "#include <rosetta/annotate.h>\n";
    std::vector<std::string> seen;
    auto                     include_once = [&](const std::string &h) {
        if (std::find(seen.begin(), seen.end(), h) == seen.end()) {
            seen.push_back(h);
            out << "#include \"" << h << "\"\n";
        }
    };
    for (const auto &c : m.classes) {
        include_once(c.header);
        for (const auto &x : c.extensions) {
            include_once(x.header); // the driver reflects ^^fn — it needs the declaration
        }
    }
    for (const auto &f : m.functions) {
        include_once(f.header);
    }
    out << "\n";
    // Foreign containers (manifest "sequences" / "matrices"): marshal like
    // std::vector<value_type> — or a vector of those rows — in the opted-in
    // expanded backends. The class headers above already declare the templates.
    // "matrices" is the same list one dimension up (rosetta::is_matrix), so the
    // two traits are emitted by one lambda parameterized on the trait names.
    const auto emit_containers = [&out](const std::vector<ContainerEntry> &entries,
                                        const char *trait, const char *spelling_trait) {
        for (const auto &s : entries) {
            if (s.exact) {
                // A concrete type: full specialization, plus the spelling the
                // adapters name it by. Composing that spelling from the template
                // and the element — what the walk does otherwise — is exactly
                // what this form exists to bypass (Eigen::VectorXd is
                // Eigen::Matrix<double, -1, 1>, not Eigen::Matrix<double>).
                out << "template <> struct rosetta::" << trait << "<" << s.name
                    << "> : std::true_type {};\n"
                    << "template <> struct rosetta::" << spelling_trait << "<" << s.name << "> {\n"
                    << "    static constexpr const char *value = \"" << s.name << "\";\n"
                    << "};\n";
            } else {
                out << "template <typename T> struct rosetta::" << trait << "<" << s.name
                    << "<T>> : std::true_type {};\n";
            }
        }
        if (!entries.empty()) {
            out << "\n";
        }
    };
    emit_containers(m.sequences, "is_sequence", "sequence_cpp_name");
    emit_containers(m.matrices, "is_matrix", "matrix_cpp_name");
    // Foreign-library interop (manifest "interop"): the walk marks every type
    // the library owns, by enclosing namespace, so no type list is needed here
    // — one specialization covers VectorXd, MatrixXd, Map, Ref and the rest.
    for (const auto &name : m.interop) {
        if (name == "eigen") {
            out << "template <> struct rosetta::interop_enabled<rosetta::eigen_interop>\n"
                << "    : std::true_type {};\n";
        }
    }
    if (!m.interop.empty()) {
        out << "\n";
    }
    for (const auto &c : m.classes) {
        out << "template <> struct rosetta::binding_info<" << c.name << "> {\n"
            << "    static constexpr const char *header = \"" << c.header << "\";\n";
        if (!c.expose.empty()) {
            out << "    static constexpr const char *expose = \"" << c.expose << "\";\n";
        }
        out << "};\n\n";
    }
    // Out-of-line annotations: bake each side-car JSON into an
    // ann_json_source<T> specialization. This TU includes the class header
    // (T is complete) before these appear, so the staleness static_assert and
    // the walk()-time merge both see them.
    for (const auto &c : m.classes) {
        if (c.annotations.empty()) {
            continue;
        }
        const std::string bytes = render_byte_array(read_file(c.annotations));
        out << "// out-of-line annotations for " << c.name << " <- "
            << c.annotations.filename().string() << "\n"
            << "template <> inline constexpr auto rosetta::detail::ann_storage<" << c.name
            << "> =\n    std::to_array<char>({" << bytes << "'\\0'});\n"
            << "template <> inline constexpr std::string_view rosetta::ann_json_source<" << c.name
            << "> =\n    std::string_view{rosetta::detail::ann_storage<" << c.name
            << ">.data(),\n                     rosetta::detail::ann_storage<" << c.name
            << ">.size() - 1};\n"
            << "static_assert(rosetta::detail::ann_keys_error<" << c.name
            << ">().empty(),\n              rosetta::detail::ann_keys_error<" << c.name
            << ">());\n\n";
    }
    return out.str();
}

static std::string render_project_gen_cpp(const Manifest &m) {
    const std::string  target = m.target();
    std::ostringstream out;
    out << "// Generated by rosetta_gen — do not edit by hand.\n"
        << "#include \"bindings.h\"\n"
        << "#include <cstdio>\n\n"
        << "int main(int argc, char **argv) {\n"
        << "    if (argc < 2) {\n"
        << "        std::fprintf(stderr, \"usage: " << target << " <out_dir>\\n\");\n"
        << "        return 1;\n"
        << "    }\n\n"
        << "    rosetta::GenerateOptions opt;\n"
        << "    opt.out_dir         = argv[1];\n"
        << "    opt.user_include    = {";
    for (std::size_t i = 0; i < m.user_include.size(); ++i) {
        out << (i ? ", " : "") << "\"" << m.user_include[i].string() << "\"";
    }
    out << "};\n"
        << "    opt.rosetta_include = \"" << m.rosetta_include.string() << "\";\n";
    // These reach the per-backend (thin) CMakeLists via GenContext; each is
    // emitted only when set (empty ⇒ generate() applies its built-in default).
    if (!m.cpp26_root.empty()) {
        out << "    opt.cpp26_root      = \"" << m.cpp26_root << "\";\n";
    }
    if (!m.cpp26_cxx.empty()) {
        out << "    opt.cpp26_cxx       = \"" << m.cpp26_cxx << "\";\n";
    }
    if (!m.cpp26_cc.empty()) {
        out << "    opt.cpp26_cc        = \"" << m.cpp26_cc << "\";\n";
    }
    if (!m.cpp26_lib.empty()) {
        out << "    opt.cpp26_lib       = \"" << m.cpp26_lib << "\";\n";
    }
    if (!m.qt_dir.empty()) {
        out << "    opt.qt_dir          = \"" << m.qt_dir << "\";\n";
    }
    // Build configuration baked into every compiled backend's CMakeLists
    // (manifest "build_type" / "optimization").
    if (!m.build_type.empty()) {
        out << "    opt.build_type      = \"" << m.build_type << "\";\n";
    }
    if (!m.optimization.empty()) {
        out << "    opt.optimization    = \"" << m.optimization << "\";\n";
    }
    // C++ standard the user sources compile with (manifest "cxx_standard");
    // absent ⇒ they build at each target's own standard.
    if (!m.cxx_standard.empty()) {
        out << "    opt.cxx_standard    = \"" << m.cxx_standard << "\";\n";
    }
    // Distribution version for the packaging artifacts (manifest "version");
    // absent ⇒ the backends stamp their own default into pyproject.toml.
    if (!m.version.empty()) {
        out << "    opt.version         = \"" << m.version << "\";\n";
    }
    // External libraries to link the bindings against (manifest "user_lib"),
    // in link order. Only the stock *-expanded backends consume these (see
    // GenerateOptions).
    if (!m.user_libs.empty()) {
        out << "    opt.user_libs       = {\n";
        for (const auto &u : m.user_libs) {
            out << "        {\"" << u.name << "\", \"" << u.dir << "\", \""
                << (u.link.empty() ? "shared" : u.link) << "\"},\n";
        }
        out << "    };\n";
    }
    // User .cpp sources compiled into each binding target (manifest "user_sources").
    if (!m.user_sources.empty()) {
        out << "    opt.user_sources    = {\n";
        for (const auto &src : m.user_sources) {
            out << "        \"" << src << "\",\n";
        }
        out << "    };\n";
    }
    // Preprocessor definitions applied to each binding target (manifest
    // "compile_definitions").
    if (!m.compile_definitions.empty()) {
        out << "    opt.compile_definitions = {\n";
        for (const auto &def : m.compile_definitions) {
            // Raw string literal: a define's VALUE is routinely a quoted string
            // (GEOGRAM_VERSION="1.10.1"), which a plain "..." would end early —
            // the driver then failed to compile on a perfectly valid manifest.
            out << "        R\"ROSETTA(" << def << ")ROSETTA\",\n";
        }
        out << "    };\n";
    }
    out << "    opt.targets         = {\n";
    for (const auto &t : m.targets) {
        // DESIGNATED initializers: TargetSpec has grown past the point where a
        // positional list is readable, and every field after `name` is optional
        // — positionally, one of them means spelling every earlier one.
        out << "        {.lang = \"" << t.lang << "\", .name = \"" << t.name << "\"";
        if (!t.link_options.empty()) {
            out << ", .link_options = {";
            for (std::size_t i = 0; i < t.link_options.size(); ++i) {
                out << (i ? ", " : "") << "\"" << t.link_options[i] << "\"";
            }
            out << "}";
        }
        const auto field = [&out](const char *name, const std::string &v) {
            if (!v.empty()) {
                out << ", ." << name << " = \"" << v << "\"";
            }
        };
        field("artifact_dir", t.out_dir);
        field("python", t.python);
        field("requires_python", t.requires_python);
        field("napi_version", t.napi_version);
        field("node_engine", t.node_engine);
        out << "},\n";
    }
    out << "    };\n";
    if (!m.functions.empty()) {
        out << "    opt.functions       = {\n";
        for (const auto &f : m.functions) {
            // With a "signature", the entry names ONE overload: `^^name` would be
            // ill-formed for the set, so the driver goes through the signature
            // path — a plain function TYPE as template argument, plus the same
            // text for the cast every backend needs to form the pointer.
            if (!f.signature.empty()) {
                out << "        rosetta::make_function_sig<" << f.signature << ">(\"" << f.name
                    << "\", \"" << f.header << "\", \"" << f.doc << "\", \"" << f.expose
                    << "\", \"" << f.signature << "\"),\n";
                continue;
            }
            out << "        rosetta::make_function<^^" << f.name << ">(\"" << f.name << "\", \""
                << f.header << "\", \"" << f.doc << "\", \"" << f.expose << "\"),\n";
        }
        out << "    };\n";
    }
    // Extension methods (manifest class "extensions"): free functions attached
    // to a bound class — generate() splices them into the class IR as methods.
    {
        bool any = false;
        for (const auto &c : m.classes) {
            any = any || !c.extensions.empty();
        }
        if (any) {
            out << "    opt.extensions      = {\n";
            for (const auto &c : m.classes) {
                for (const auto &x : c.extensions) {
                    out << "        {\"" << c.name << "\", rosetta::make_function<^^" << x.name
                        << ">(\"" << x.name << "\", \"" << x.header << "\", \"" << x.doc
                        << "\", \"" << x.expose << "\")},\n";
                }
            }
            out << "    };\n";
        }
    }
    // "final" classes: no trampoline (host-language overriding off) — see
    // ClassEntry::final_.
    {
        bool any = false;
        for (const auto &c : m.classes) {
            any = any || c.final_;
        }
        if (any) {
            out << "    opt.final_classes   = {";
            bool first = true;
            for (const auto &c : m.classes) {
                if (c.final_) {
                    out << (first ? "" : ", ") << "\"" << c.name << "\"";
                    first = false;
                }
            }
            out << "};\n";
        }
    }
    // "out_params": the parameters the manifest declares as outputs, applied
    // to the IR by generate() after the walk.
    if (!m.out_params.empty()) {
        out << "    opt.out_params      = {\n";
        for (const auto &[key, indices] : m.out_params) {
            out << "        {\"" << key << "\", {";
            for (std::size_t i = 0; i < indices.size(); ++i) {
                out << (i ? ", " : "") << indices[i];
            }
            out << "}},\n";
        }
        out << "    };\n";
    }
    // Doc comments harvested from the bound headers (manifest "doc_comments",
    // on unless turned off). Emitted as data — every string goes out as a raw
    // literal, because a docstring routinely contains quotes, backslashes and
    // newlines, and a default argument may itself be a quoted string.
    if (!m.harvested_docs.empty()) {
        out << "    opt.doc_comments    = {\n";
        for (const auto &kv : m.harvested_docs) {
            out << "        {" << str_lit(kv.first) << ", {\n";
            for (const DocEntryInfo &e : kv.second) {
                out << "            {.doc = " << str_lit(e.doc)
                    << ", .returns = " << str_lit(e.returns) << ", .params = {";
                for (std::size_t i = 0; i < e.params.size(); ++i) {
                    const DocParamInfo &p = e.params[i];
                    out << (i ? ", " : "") << "{" << str_lit(p.name) << ", " << str_lit(p.doc)
                        << ", " << str_lit(p.default_text) << "}";
                }
                out << "}, .is_function = " << (e.is_function ? "true" : "false") << "},\n";
            }
            out << "        }},\n";
        }
        out << "    };\n";
    }
    // "module_init": the statements the module runs when it loads, and the
    // headers that declare them. Emitted as data — the driver never parses
    // them; each backend drops them at the top of its module entry point.
    if (!m.module_init.statements.empty()) {
        out << "    opt.init_headers    = {";
        for (std::size_t i = 0; i < m.module_init.headers.size(); ++i) {
            out << (i ? ", " : "") << "\"" << m.module_init.headers[i] << "\"";
        }
        out << "};\n";
        out << "    opt.init_statements = {\n";
        for (const auto &st : m.module_init.statements) {
            out << "        R\"ROSETTA(" << st << ")ROSETTA\",\n";
        }
        out << "    };\n";
    }
    // "generated_headers": already-resolved text (template + substitutions were
    // applied when the manifest was read), baked in as a raw string literal so
    // the driver depends on no file it would have to find again at run time.
    if (!m.generated_headers.empty()) {
        out << "    opt.generated_headers = {\n";
        for (const auto &g : m.generated_headers) {
            out << "        {\"" << g.path << "\", R\"ROSETTA(" << g.content << ")ROSETTA\"},\n";
        }
        out << "    };\n";
    }
    out << "\n";
    out << "    rosetta::generate<";
    for (std::size_t i = 0; i < m.classes.size(); ++i) {
        out << (i ? ", " : "") << m.classes[i].name;
    }
    out << ">(opt);\n";
    out << "\n    std::fprintf(stderr, \"wrote scaffolding to %s\\n\",\n"
        << "                 opt.out_dir.string().c_str());\n"
        << "    return 0;\n"
        << "}\n";
    return out.str();
}

static std::string render_cmakelists(const Manifest &m) {
    const std::string  target = "generator"; // m.target();
    std::ostringstream out;
    const std::string cpp26_root = m.cpp26_root.empty() ? kDefaultCpp26Root : m.cpp26_root;
    const std::string cpp26_cxx  = m.cpp26_cxx.empty() ? kDefaultCpp26Cxx : m.cpp26_cxx;
    const std::string cpp26_cc   = m.cpp26_cc.empty() ? kDefaultCpp26Cc : m.cpp26_cc;
    const std::string cpp26_lib  = m.cpp26_lib.empty() ? kDefaultCpp26Lib : m.cpp26_lib;
    out << "# Generated by rosetta_gen — do not edit by hand.\n"
        << "cmake_minimum_required(VERSION 3.28)\n\n"
        << "set(CLANG_P2996_ROOT \"" << cpp26_root << "\"\n"
        << "    CACHE PATH \"C++26 / P2996 reflection toolchain root (clang-p2996 build dir)\")\n"
        << "set(ROSETTA_CXX_COMPILER \"" << cpp26_cxx << "\"\n"
        << "    CACHE FILEPATH \"C++26 / P2996 C++ compiler\")\n"
        << "set(ROSETTA_C_COMPILER \"" << cpp26_cc << "\"\n"
        << "    CACHE FILEPATH \"C++26 / P2996 C compiler\")\n"
        << "set(ROSETTA_STDLIB \"" << cpp26_lib << "\"\n"
        << "    CACHE PATH \"Directory holding the fork's libc++ / libc++abi (-L and -rpath)\")\n"
        << "if(NOT CMAKE_CXX_COMPILER)\n"
        << "    set(CMAKE_C_COMPILER   \"${ROSETTA_C_COMPILER}\")\n"
        << "    set(CMAKE_CXX_COMPILER \"${ROSETTA_CXX_COMPILER}\")\n"
        << "endif()\n\n"
        << "project(" << target << " CXX)\n\n"
        << "set(CMAKE_CXX_STANDARD 26)\n"
        << "set(CMAKE_CXX_STANDARD_REQUIRED ON)\n"
        << "set(CMAKE_CXX_EXTENSIONS OFF)\n"
        << "set(CMAKE_CXX_SCAN_FOR_MODULES OFF)\n\n"
        << "# Place the built binary in the parent folder (where rosetta_gen\n"
        << "# was invoked), not in this generation folder's build tree.\n"
        << "set(CMAKE_RUNTIME_OUTPUT_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}/..)\n\n";

    // add_executable with the driver source plus any plugin sources.
    out << "add_executable(" << target << " " << m.target() << ".cpp";
    for (const auto &p : m.plugins) {
        out << "\n    " << p;
    }
    out << ")\n\n";

    out << "target_include_directories(" << target << " PRIVATE\n";
    for (const auto &inc : m.user_include) {
        out << "    " << inc.string() << "\n";
    }
    out << "    " << m.rosetta_include.string() << ")\n\n";

    // The driver includes the bound headers (the reflection walk), so it must
    // see the same preprocessor definitions the bindings will be built with.
    if (!m.compile_definitions.empty()) {
        out << "target_compile_definitions(" << target << " PRIVATE\n";
        for (std::size_t i = 0; i < m.compile_definitions.size(); ++i) {
            out << "    " << m.compile_definitions[i]
                << (i + 1 < m.compile_definitions.size() ? "\n" : ")\n\n");
        }
    }

    out << "target_compile_options(" << target << " PRIVATE\n"
        << "    -freflection -freflection-latest -fexperimental-library "
           "-fannotation-attributes)\n\n"
        << "target_link_options(" << target << " PRIVATE\n"
        << "    -nostdlib++ -L${ROSETTA_STDLIB} -Wl,-rpath,${ROSETTA_STDLIB}\n"
        << "    -lc++ -lc++abi)\n";

    // If the bound headers only declare the API (bodies in an external library),
    // the driver links against it too: the reflection walk instantiates each
    // bound type (e.g. to read default-constructed field values), so it needs
    // the out-of-line definitions at link AND run time (hence rpath).
    if (!m.user_libs.empty()) {
        out << "\n# External user libraries (manifest \"user_lib\"), in link order — the\n"
               "# bound library plus the pre-built ones it depends on. `link` (\"shared\" |\n"
               "# \"static\") picks the preferred form; we fall back to whichever is present\n"
               "# and reference it by full path (never mistaken for a same-named target).\n"
            << "set(_rosetta_rpath \"\")\n";
        for (std::size_t i = 0; i < m.user_libs.size(); ++i) {
            const auto       &u    = m.user_libs[i];
            const std::string n    = std::to_string(i);
            const std::string link = u.link.empty() ? "shared" : u.link;
            out << "set(ROSETTA_USER_LIB_" << n << " \"" << u.name << "\")\n"
                << "set(ROSETTA_USER_LIB_DIR_" << n << " \"" << u.dir << "\")\n"
                << "set(ROSETTA_USER_LIB_LINK_" << n << " \"" << link << "\")\n"
                << "set(_rosetta_shared \"${ROSETTA_USER_LIB_DIR_" << n
                << "}/${CMAKE_SHARED_LIBRARY_PREFIX}"
                   "${ROSETTA_USER_LIB_" << n << "}${CMAKE_SHARED_LIBRARY_SUFFIX}\")\n"
                << "set(_rosetta_static \"${ROSETTA_USER_LIB_DIR_" << n
                << "}/${CMAKE_STATIC_LIBRARY_PREFIX}"
                   "${ROSETTA_USER_LIB_" << n << "}${CMAKE_STATIC_LIBRARY_SUFFIX}\")\n"
                << "if(ROSETTA_USER_LIB_LINK_" << n << " STREQUAL \"static\")\n"
                << "    set(_rosetta_order \"${_rosetta_static}\" \"${_rosetta_shared}\")\n"
                << "else()\n"
                << "    set(_rosetta_order \"${_rosetta_shared}\" \"${_rosetta_static}\")\n"
                << "endif()\n"
                << "set(_rosetta_lib \"\")\n"
                << "foreach(_cand IN LISTS _rosetta_order)\n"
                << "    if(EXISTS \"${_cand}\")\n"
                << "        set(_rosetta_lib \"${_cand}\")\n"
                << "        break()\n"
                << "    endif()\n"
                << "endforeach()\n"
                << "if(NOT _rosetta_lib)\n"
                << "    set(_rosetta_lib \"-l${ROSETTA_USER_LIB_" << n << "}\")\n"
                << "endif()\n"
                << "target_link_directories(" << target << " PRIVATE ${ROSETTA_USER_LIB_DIR_" << n
                << "})\n"
                << "target_link_libraries(" << target << " PRIVATE \"${_rosetta_lib}\")\n"
                << "list(APPEND _rosetta_rpath \"${ROSETTA_USER_LIB_DIR_" << n << "}\")\n";
        }
        out << "list(REMOVE_DUPLICATES _rosetta_rpath)\n"
            << "set_target_properties(" << target << " PROPERTIES\n"
            << "    BUILD_RPATH \"${_rosetta_rpath}\")\n";
    }
    return out.str();
}

// Emit the generator project tree (bindings.h + <generator_name>.cpp +
// CMakeLists.txt) — shared by the plain generate mode and --build.
// Returns whether any emitted file actually changed.
bool emit_generator_project(const Manifest &m, const fs::path &out_dir) {
    const std::string target  = m.target();
    bool              changed = false;
    changed |= write_file_if_changed(out_dir / "bindings.h", render_bindings_h(m));
    changed |= write_file_if_changed(out_dir / (target + ".cpp"), render_project_gen_cpp(m));
    changed |= write_file_if_changed(out_dir / "CMakeLists.txt", render_cmakelists(m));
    std::fprintf(stderr, "%s %s/{bindings.h, %s.cpp, CMakeLists.txt}\n",
                 changed ? "wrote" : "unchanged:", out_dir.string().c_str(), target.c_str());
    return changed;
}
